import type { ImplementationSchemaConfig, WidgetManifestEntry } from '../manifest.types.js';

/** A plain JSON schema object as produced by the builders. */
export type SchemaObject = Record<string, unknown>;

const JSON_SCHEMA_DIALECT = 'https://json-schema.org/draft/2020-12/schema';

function generatedFileComment(config: ImplementationSchemaConfig): string {
  return (
    `GENERATED by ${config.generatorPath} ` +
    'from src/lib/widget-manifest.ts. DO NOT EDIT. Regenerate with `npm run generate:schemas`.'
  );
}

function schemaBearingEntries(
  manifest: readonly WidgetManifestEntry[],
): ReadonlyArray<WidgetManifestEntry & { schemaFile: string }> {
  return manifest.filter(
    (entry): entry is WidgetManifestEntry & { schemaFile: string } =>
      entry.schemaFile !== undefined,
  );
}

/**
 * Builds the implementation's `widgets.schema.json`: the `formWidget` union and
 * the `knownWidgetTypes` enum, derived from one manifest so they cannot disagree.
 * @param config - The implementation's schema configuration.
 * @returns The schema object, ready to be serialized.
 */
export function buildWidgetsSchema(config: ImplementationSchemaConfig): SchemaObject {
  const withSchema = schemaBearingEntries(config.manifest);
  const knownTypeEntries = config.includeSchemalessTypesInKnownWidgetTypes
    ? config.manifest
    : withSchema;
  return {
    $schema: JSON_SCHEMA_DIALECT,
    $id: `${config.idBase}widgets.schema.json`,
    $comment: generatedFileComment(config),
    title: `Golem ${config.implementation} widgets`,
    $defs: {
      knownWidgetTypes: {
        description:
          'Built-in widget `type` identifiers. Used to exclude built-ins from the custom-widget fallback so every widget matches exactly one schema. Types listed here without a component schema are not expressible in JSON and are rejected entirely instead of validating as custom widgets.',
        enum: knownTypeEntries.map((entry) => entry.type),
      },
      formWidget: {
        description:
          'A form widget: one of the built-in component schemas, the custom-widget fallback, or a reference to an external chunk file.',
        oneOf: [
          ...withSchema.map((entry) => ({ $ref: `./components/${entry.schemaFile}` })),
          ...(config.includeCustomWidgetFallback
            ? [{ $ref: './components/custom.schema.json' }]
            : []),
          { $ref: './core/common.schema.json#/$defs/chunkRef' },
        ],
      },
    },
  };
}

/**
 * Builds the implementation's `form.schema.json` envelope: the document root a
 * form definition file validates against.
 * @param config - The implementation's schema configuration.
 * @returns The schema object, ready to be serialized.
 */
export function buildFormEnvelope(config: ImplementationSchemaConfig): SchemaObject {
  return {
    $schema: JSON_SCHEMA_DIALECT,
    $id: `${config.idBase}form.schema.json`,
    $comment: generatedFileComment(config),
    title: config.formTitle,
    type: 'object',
    properties: {
      $schema: {
        type: 'string',
      },
      states: {
        type: 'object',
        description: config.statesDescription,
        additionalProperties: {
          $ref: './core/common.schema.json#/$defs/reactiveExpression',
        },
      },
      form: {
        type: 'array',
        description: 'The ordered list of widgets that make up the form body',
        items: {
          $ref: './widgets.schema.json#/$defs/formWidget',
        },
      },
      autocomplete: {
        type: 'string',
        description:
          'HTML `autocomplete` attribute applied to the `<form>` element (e.g. `on`, `off`)',
      },
    },
    required: ['form'],
    additionalProperties: false,
  };
}

/**
 * Builds the implementation's `layout-widget.schema.json`: the union of the
 * layout-kind manifest entries, used by chunk files and repeater templates.
 * @param config - The implementation's schema configuration.
 * @returns The schema object, ready to be serialized.
 */
export function buildLayoutWidgetSchema(config: ImplementationSchemaConfig): SchemaObject {
  const layoutEntries = schemaBearingEntries(config.manifest).filter(
    (entry) => entry.kind === 'layout',
  );
  // An empty oneOf is invalid JSON Schema and would silently reject every input.
  if (layoutEntries.length === 0) {
    throw new Error(
      `The ${config.implementation} manifest has no layout entries with a schema file, ` +
        'so layout-widget.schema.json cannot be generated: an empty oneOf is invalid JSON Schema.',
    );
  }
  return {
    $schema: JSON_SCHEMA_DIALECT,
    $id: `${config.idBase}layout-widget.schema.json`,
    $comment: generatedFileComment(config),
    title: 'Golem Layout Widget',
    oneOf: layoutEntries.map((entry) => ({ $ref: `./components/${entry.schemaFile}` })),
  };
}

const VALID_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function importNameForSchemaFile(schemaFile: string): string {
  const stem = schemaFile.replace(/\.schema\.json$/, '');
  const words = stem.split(/[^A-Za-z0-9_$]+/).filter((word) => word.length > 0);
  const camelCased = words
    .map((word, index) => (index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join('');
  const name = `${camelCased}Schema`;
  if (!VALID_IDENTIFIER.test(name)) {
    throw new Error(
      `Cannot derive a TypeScript identifier from schema file name "${schemaFile}" (got "${name}").`,
    );
  }
  return name;
}

/** Widget types that are not valid identifiers (e.g. `date-range`) become quoted object keys. */
function objectKeyForWidgetType(type: string): string {
  return VALID_IDENTIFIER.test(type) ? type : `'${type}'`;
}

/**
 * Builds the source of the implementation schema package's `src/index.ts`:
 * schema imports, re-exports, and the `COMPONENT_SCHEMAS_BY_TYPE` map.
 *
 * Every schema is imported as `<name>Json` and re-exported as an annotated
 * `<name>` constant. The annotation keeps `.json` imports out of the emitted
 * `index.d.ts`, so a consumer of the published package needs neither
 * `resolveJsonModule` nor a `type: "json"` import attribute.
 * @param config - The implementation's schema configuration.
 * @returns The TypeScript source text (unformatted, run it through prettier).
 */
export function buildSchemasPackageIndex(config: ImplementationSchemaConfig): string {
  const withSchema = schemaBearingEntries(config.manifest);
  const schemaExports: Array<{ name: string; path: string }> = [
    { name: 'commonSchema', path: 'core/common.schema.json' },
    ...config.libRootSchemaFiles.map((file) => ({
      name: importNameForSchemaFile(file),
      path: file,
    })),
    { name: 'formSchema', path: 'form.schema.json' },
    { name: 'layoutWidgetSchema', path: 'layout-widget.schema.json' },
    { name: 'widgetsSchema', path: 'widgets.schema.json' },
    ...withSchema.map((entry) => ({
      name: importNameForSchemaFile(entry.schemaFile),
      path: `components/${entry.schemaFile}`,
    })),
    ...(config.includeCustomWidgetFallback
      ? [{ name: 'customSchema', path: 'components/custom.schema.json' }]
      : []),
  ];
  // A duplicate export name (e.g. a libRootSchemaFiles entry named common.schema.json)
  // would emit an index that prettier accepts but the build rejects.
  const pathByExportName = new Map<string, string>();
  for (const { name, path } of schemaExports) {
    const existingPath = pathByExportName.get(name);
    if (existingPath !== undefined) {
      throw new Error(
        `Duplicate export name "${name}", derived from both "${existingPath}" and "${path}".`,
      );
    }
    pathByExportName.set(name, path);
  }
  const mapEntries = withSchema.map(
    (entry) =>
      `  ${objectKeyForWidgetType(entry.type)}: ${importNameForSchemaFile(entry.schemaFile)},`,
  );
  const lines = [
    '// GENERATED by ' + config.generatorPath + ' from src/lib/widget-manifest.ts. DO NOT EDIT.',
    '// Regenerate with `npm run generate:schemas`.',
    ...schemaExports.map(({ name, path }) => `import ${name}Json from './lib/${path}';`),
    '',
    ...schemaExports.map(
      ({ name }) => `export const ${name}: Record<string, unknown> = ${name}Json;`,
    ),
    '',
    '/** Component schemas keyed by widget `type`. Excludes the custom fallback and schema-less types. */',
    'export const COMPONENT_SCHEMAS_BY_TYPE = {',
    ...mapEntries,
    '} as const;',
  ];
  return lines.join('\n') + '\n';
}
