import type { ImplementationSchemaConfig, WidgetManifestEntry } from '../manifest.types';

/** A plain JSON schema object as produced by the builders. */
export type SchemaObject = Record<string, unknown>;

const JSON_SCHEMA_DIALECT = 'https://json-schema.org/draft/2020-12/schema';

function generatedFileComment(config: ImplementationSchemaConfig): string {
  return (
    `GENERATED by libs/${config.implementation}/schemas/tools/generate-schemas.ts ` +
    'from src/lib/widget-manifest.ts. DO NOT EDIT. Regenerate with `npm run generate:schemas`.'
  );
}

function schemaBearingEntries(
  manifest: readonly WidgetManifestEntry[],
): ReadonlyArray<WidgetManifestEntry & { schemaFile: string }> {
  return manifest.filter(
    (entry): entry is WidgetManifestEntry & { schemaFile: string } =>
      entry.schemaFile !== undefined,
  );
}

/**
 * Builds the implementation's `widgets.schema.json`: the `formWidget` union and
 * the `knownWidgetTypes` enum, derived from one manifest so they cannot disagree.
 * @param config - The implementation's schema configuration.
 * @returns The schema object, ready to be serialized.
 */
export function buildWidgetsSchema(config: ImplementationSchemaConfig): SchemaObject {
  const withSchema = schemaBearingEntries(config.manifest);
  const knownTypeEntries = config.includeSchemalessTypesInKnownWidgetTypes
    ? config.manifest
    : withSchema;
  return {
    $schema: JSON_SCHEMA_DIALECT,
    $id: `${config.idBase}widgets.schema.json`,
    $comment: generatedFileComment(config),
    title: `Golem ${config.implementation} widgets`,
    $defs: {
      knownWidgetTypes: {
        description:
          'Built-in widget `type` identifiers. Used to exclude built-ins from the custom-widget fallback so every widget matches exactly one schema. Types listed here without a component schema are not expressible in JSON and are rejected entirely instead of validating as custom widgets.',
        enum: knownTypeEntries.map((entry) => entry.type),
      },
      formWidget: {
        description:
          'A form widget: one of the built-in component schemas, the custom-widget fallback, or a reference to an external chunk file.',
        oneOf: [
          ...withSchema.map((entry) => ({ $ref: `./components/${entry.schemaFile}` })),
          { $ref: './components/custom.schema.json' },
          { $ref: './core/common.schema.json#/$defs/chunkRef' },
        ],
      },
    },
  };
}

/**
 * Builds the implementation's `form.schema.json` envelope: the document root a
 * form definition file validates against.
 * @param config - The implementation's schema configuration.
 * @returns The schema object, ready to be serialized.
 */
export function buildFormEnvelope(config: ImplementationSchemaConfig): SchemaObject {
  return {
    $schema: JSON_SCHEMA_DIALECT,
    $id: `${config.idBase}form.schema.json`,
    $comment: generatedFileComment(config),
    title: 'Golem Form DSL',
    type: 'object',
    properties: {
      $schema: {
        type: 'string',
      },
      states: {
        type: 'object',
        description:
          'Named boolean conditions keyed by state name, each mapping to a reactive expression. States serve two purposes: (1) gating widget visibility via `include.in` / `exclude.from`; (2) overriding individual widget properties when a state is active by appending `".<stateName>"` to any property key - e.g. `"label.myState": "Active label"` or `"props.hint.myState": "Active hint"`. Root-level suffixable props: `label`, `disabled`, `readonly`, `validator`, `size`. Any key inside `props` can also be suffixed.',
        additionalProperties: {
          $ref: './core/common.schema.json#/$defs/reactiveExpression',
        },
      },
      form: {
        type: 'array',
        description: 'The ordered list of widgets that make up the form body',
        items: {
          $ref: './widgets.schema.json#/$defs/formWidget',
        },
      },
      autocomplete: {
        type: 'string',
        description:
          'HTML `autocomplete` attribute applied to the `<form>` element (e.g. `on`, `off`)',
      },
    },
    required: ['form'],
    additionalProperties: false,
  };
}

/**
 * Builds the implementation's `layout-widget.schema.json`: the union of the
 * layout-kind manifest entries, used by chunk files and repeater templates.
 * @param config - The implementation's schema configuration.
 * @returns The schema object, ready to be serialized.
 */
export function buildLayoutWidgetSchema(config: ImplementationSchemaConfig): SchemaObject {
  const layoutEntries = schemaBearingEntries(config.manifest).filter(
    (entry) => entry.kind === 'layout',
  );
  return {
    $schema: JSON_SCHEMA_DIALECT,
    $id: `${config.idBase}layout-widget.schema.json`,
    $comment: generatedFileComment(config),
    title: 'Golem Layout Widget',
    oneOf: layoutEntries.map((entry) => ({ $ref: `./components/${entry.schemaFile}` })),
  };
}

function importNameForSchemaFile(schemaFile: string): string {
  return `${schemaFile.replace(/\.schema\.json$/, '')}Schema`;
}

/**
 * Builds the source of the implementation schema package's `src/index.ts`:
 * schema imports, re-exports, and the `COMPONENT_SCHEMAS_BY_TYPE` map.
 * @param config - The implementation's schema configuration.
 * @returns The TypeScript source text (unformatted, run it through prettier).
 */
export function buildSchemasPackageIndex(config: ImplementationSchemaConfig): string {
  const withSchema = schemaBearingEntries(config.manifest);
  const componentImports = [
    ...withSchema.map(
      (entry) =>
        `import ${importNameForSchemaFile(entry.schemaFile)} from './lib/components/${entry.schemaFile}';`,
    ),
    `import customSchema from './lib/components/custom.schema.json';`,
  ];
  const componentExportNames = [
    ...withSchema.map((entry) => importNameForSchemaFile(entry.schemaFile)),
    'customSchema',
  ];
  const mapEntries = withSchema.map(
    (entry) => `  ${entry.type}: ${importNameForSchemaFile(entry.schemaFile)},`,
  );
  const lines = [
    '// GENERATED by libs/' +
      config.implementation +
      '/schemas/tools/generate-schemas.ts from src/lib/widget-manifest.ts. DO NOT EDIT.',
    '// Regenerate with `npm run generate:schemas`.',
    ...componentImports,
    `export { default as commonSchema } from './lib/core/common.schema.json';`,
    `export { default as validatorsSchema } from './lib/core/validators.schema.json';`,
    `export { default as formSchema } from './lib/form.schema.json';`,
    `export { default as layoutWidgetSchema } from './lib/layout-widget.schema.json';`,
    `export { default as widgetsSchema } from './lib/widgets.schema.json';`,
    `export { ${config.implementation}CoreRegistrations } from './lib/core-registrations';`,
    `export { ${componentExportNames.join(', ')} };`,
    '',
    '/** Component schemas keyed by widget `type`. Excludes the custom fallback and schema-less types. */',
    'export const COMPONENT_SCHEMAS_BY_TYPE = {',
    ...mapEntries,
    '} as const;',
  ];
  return lines.join('\n') + '\n';
}
