import { describe, expect, it } from 'vitest';
import type { ImplementationSchemaConfig } from '../manifest.types';
import { buildEditorBundle, type SchemaObject } from '../../index';

const config: ImplementationSchemaConfig = {
  implementation: 'kendo',
  idBase: 'https://example.com/schemas/kendo/',
  generatorPath: 'tools/generate-schemas.mjs',
  manifestPath: 'schemas.config.mjs',
  regenerateCommand: 'npx @golemui/schemas generate',
  formTitle: 'Kendo Form DSL',
  statesDescription: 'Kendo states description.',
  manifest: [{ type: 'textbox', schemaFile: 'textbox.schema.json', kind: 'input' }],
  libRootSchemaFiles: ['validators.schema.json'],
  includeSchemalessTypesInKnownWidgetTypes: false,
  includeCustomWidgetFallback: false,
};

// A tree with the shape the generator produces: an envelope pointing at the widget
// union, a component reaching up to the vendored core, and a same-document ref.
const tree: Record<string, SchemaObject> = {
  'form.schema.json': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://example.com/schemas/kendo/form.schema.json',
    $comment: 'GENERATED, do not edit.',
    title: 'Kendo Form DSL',
    type: 'object',
    properties: {
      form: { type: 'array', items: { $ref: './widgets.schema.json#/$defs/formWidget' } },
    },
  },
  'widgets.schema.json': {
    $id: 'https://example.com/schemas/kendo/widgets.schema.json',
    $defs: {
      formWidget: {
        oneOf: [
          { $ref: './components/textbox.schema.json' },
          { $ref: './core/common.schema.json#/$defs/chunkRef' },
        ],
      },
    },
  },
  'components/textbox.schema.json': {
    $id: 'https://example.com/schemas/kendo/components/textbox.schema.json',
    $defs: { labelProp: { type: 'string' } },
    allOf: [{ $ref: '../core/common.schema.json#/$defs/baseWidget' }],
    properties: { label: { $ref: '#/$defs/labelProp' } },
  },
  'core/common.schema.json': {
    $id: 'https://example.com/schemas/kendo/core/common.schema.json',
    $defs: {
      baseWidget: { type: 'object' },
      chunkRef: {
        type: 'object',
        // A property whose name is literally `$ref`: the chunk reference widget.
        properties: { $ref: { type: 'string', description: 'Relative path to a chunk file' } },
        required: ['$ref'],
      },
    },
  },
};

function readFromTree(libRelativePath: string): SchemaObject {
  const schema = tree[libRelativePath];
  if (schema === undefined) {
    throw new Error(`No test schema at ${libRelativePath}`);
  }
  return schema;
}

describe('buildEditorBundle', () => {
  it('inlines every reachable file under $defs, keyed by base name', () => {
    const bundle = buildEditorBundle(config, readFromTree) as any;
    expect(Object.keys(bundle.$defs).sort()).toEqual(['common', 'form', 'textbox', 'widgets']);
    expect(bundle.$ref).toBe('#/$defs/form');
    expect(bundle.title).toBe('Kendo Form DSL (editor bundle)');
  });

  it('drops the per-file $schema, $id and $comment so nothing is fetched by URL', () => {
    const bundle = buildEditorBundle(config, readFromTree) as any;
    const serialized = JSON.stringify(bundle);
    expect(serialized).not.toContain('https://example.com/schemas/kendo/');
    for (const inlined of Object.values<any>(bundle.$defs)) {
      expect(inlined.$id).toBeUndefined();
      expect(inlined.$schema).toBeUndefined();
    }
  });

  it('rewrites sibling, nested and parent-relative refs to same-document pointers', () => {
    const bundle = buildEditorBundle(config, readFromTree) as any;
    expect(bundle.$defs.form.properties.form.items.$ref).toBe('#/$defs/widgets/$defs/formWidget');
    expect(bundle.$defs.widgets.$defs.formWidget.oneOf).toEqual([
      { $ref: '#/$defs/textbox' },
      { $ref: '#/$defs/common/$defs/chunkRef' },
    ]);
    expect(bundle.$defs.textbox.allOf).toEqual([{ $ref: '#/$defs/common/$defs/baseWidget' }]);
  });

  it('rewrites a same-document ref onto the file that holds it', () => {
    const bundle = buildEditorBundle(config, readFromTree) as any;
    expect(bundle.$defs.textbox.properties.label.$ref).toBe('#/$defs/textbox/$defs/labelProp');
  });

  // `properties: { "$ref": ... }` declares a property named `$ref`, not a reference.
  it('leaves a property literally named $ref untouched', () => {
    const bundle = buildEditorBundle(config, readFromTree) as any;
    expect(bundle.$defs.common.$defs.chunkRef.properties.$ref).toEqual({
      type: 'string',
      description: 'Relative path to a chunk file',
    });
    expect(bundle.$defs.common.$defs.chunkRef.required).toEqual(['$ref']);
  });

  it('carries the generator marker from the config', () => {
    const bundle = buildEditorBundle(config, readFromTree) as any;
    expect(bundle.$comment).toContain('GENERATED by tools/generate-schemas.mjs');
    expect(bundle.$comment).toContain('schemas.config.mjs');
    expect(bundle.$comment).toContain('npx @golemui/schemas generate');
  });

  it('throws when two files share a base name, which would overwrite a $defs entry', () => {
    const collidingTree: Record<string, SchemaObject> = {
      ...tree,
      'widgets.schema.json': {
        $defs: { formWidget: { $ref: './components/widgets.schema.json' } },
      },
      'components/widgets.schema.json': { type: 'object' },
    };
    expect(() => buildEditorBundle(config, (path) => collidingTree[path] as SchemaObject)).toThrow(
      /both use the \$defs key "widgets"/,
    );
  });

  it('reports the missing file when a ref points outside the tree', () => {
    expect(() =>
      buildEditorBundle(config, (path) => {
        if (path === 'components/textbox.schema.json') {
          throw new Error(`No test schema at ${path}`);
        }
        return readFromTree(path);
      }),
    ).toThrow(/components\/textbox\.schema\.json/);
  });
});
