// End-to-end check of `init`: scaffold a tree into a temp directory, then treat the
// result exactly as an implementer would. Registers every file into Ajv 2020 by its
// own `$id` and validates the scaffolded example form, so a broken template or a
// broken builder fails here rather than in someone else's project.

import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import Ajv2020 from 'ajv/dist/2020';
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { runCli } from './run';

const ID_BASE = 'https://example.com/schemas/kendo/';

let packageRoot: string;

function listFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true, recursive: true })
    .filter((entry) => entry.isFile())
    .map((entry) => relative(packageRoot, join(entry.parentPath, entry.name)))
    .sort();
}

function readJson(relativePath: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(packageRoot, relativePath), 'utf-8'));
}

function readExampleForm(): { form: Array<Record<string, unknown>> } {
  return readJson('examples/example.form.json') as unknown as {
    form: Array<Record<string, unknown>>;
  };
}

function firstChildOf(form: { form: Array<Record<string, unknown>> }): Record<string, unknown> {
  return (form.form[0]['children'] as Array<Record<string, unknown>>)[0] as Record<string, unknown>;
}

beforeAll(async () => {
  vi.spyOn(console, 'log').mockImplementation(() => undefined);
  packageRoot = join(mkdtempSync(join(tmpdir(), 'golemui-scaffold-')), 'schemas');
  const exitCode = await runCli([
    'init',
    '--name',
    'kendo',
    // Deliberately without the trailing slash: the CLI has to add it.
    '--id-base',
    'https://example.com/schemas/kendo',
    '--dir',
    packageRoot,
  ]);
  expect(exitCode).toBe(0);
});

afterAll(() => {
  vi.restoreAllMocks();
  rmSync(packageRoot, { recursive: true, force: true });
});

describe('the scaffolded tree', () => {
  it('has the documented layout and nothing else', () => {
    expect(listFiles(packageRoot)).toEqual([
      'examples/example.form.json',
      'schemas.config.mjs',
      'src/index.ts',
      'src/lib/components/example-input.schema.json',
      'src/lib/components/flex.schema.json',
      'src/lib/core/common.schema.json',
      'src/lib/form.editor.schema.json',
      'src/lib/form.schema.json',
      'src/lib/layout-widget.schema.json',
      'src/lib/validators.schema.json',
      'src/lib/widgets.schema.json',
      'test/schemas.spec.ts',
    ]);
  });

  it('rebases every $id onto the id base, adding the missing trailing slash', () => {
    expect(readJson('src/lib/form.schema.json')['$id']).toBe(`${ID_BASE}form.schema.json`);
    expect(readJson('src/lib/core/common.schema.json')['$id']).toBe(
      `${ID_BASE}core/common.schema.json`,
    );
    expect(readJson('src/lib/components/flex.schema.json')['$id']).toBe(
      `${ID_BASE}components/flex.schema.json`,
    );
  });

  it('marks generated files as generated and starter files as owned by the implementer', () => {
    expect(readJson('src/lib/widgets.schema.json')['$comment']).toContain(
      'GENERATED by @golemui/schemas generate from schemas.config.mjs',
    );
    expect(readJson('src/lib/validators.schema.json')['$comment']).toContain('STARTER TEMPLATE');
    expect(readJson('src/lib/components/flex.schema.json')['$comment']).toContain(
      'STARTER TEMPLATE',
    );
  });

  it('leaves no unsubstituted placeholder anywhere', () => {
    for (const file of listFiles(packageRoot)) {
      expect(readFileSync(join(packageRoot, file), 'utf-8'), file).not.toMatch(/__[A-Z_]+__/);
    }
  });

  it('exposes the validator entry pointer every component schema references', () => {
    const validators = readJson('src/lib/validators.schema.json');
    expect((validators['$defs'] as Record<string, unknown>)['validator']).toBeDefined();
  });
});

describe('the scaffolded tree in Ajv', () => {
  let validate: ReturnType<Ajv2020['getSchema']>;

  beforeAll(() => {
    const ajv = new Ajv2020({ allErrors: false, strict: false });
    // The order the scaffolded spec documents: leaves, then aggregates, envelope last.
    const registrationOrder = [
      'src/lib/core/common.schema.json',
      'src/lib/validators.schema.json',
      'src/lib/widgets.schema.json',
      'src/lib/layout-widget.schema.json',
      'src/lib/components/flex.schema.json',
      'src/lib/components/example-input.schema.json',
      'src/lib/form.schema.json',
    ].map(readJson);
    for (const schema of registrationOrder) {
      if (!ajv.schemas[schema['$id'] as string]) {
        ajv.addSchema(schema);
      }
    }
    validate = ajv.getSchema(`${ID_BASE}form.schema.json`);
    expect(validate).toBeDefined();
  });

  it('validates the scaffolded example form', () => {
    const valid = validate?.(readExampleForm());
    expect(valid, JSON.stringify(validate?.errors, null, 2)).toBe(true);
  });

  it('rejects an unknown widget type', () => {
    const form = readExampleForm();
    firstChildOf(form)['type'] = 'not-a-widget';
    expect(validate?.(form)).toBe(false);
  });

  it('rejects an unknown validator key', () => {
    const form = readExampleForm();
    firstChildOf(form)['validator'] = { type: 'string', required: true, notAKey: 1 };
    expect(validate?.(form)).toBe(false);
  });

  it('rejects an unknown key inside props', () => {
    const form = readExampleForm();
    firstChildOf(form)['props'] = { notAProp: true };
    expect(validate?.(form)).toBe(false);
  });
});

describe('the editor bundle', () => {
  it('inlines the whole tree, so an editor fetches nothing', () => {
    const text = readFileSync(join(packageRoot, 'src/lib/form.editor.schema.json'), 'utf-8');
    expect(text).not.toContain(ID_BASE);
    const bundle = JSON.parse(text);
    expect(Object.keys(bundle.$defs).sort()).toEqual([
      'common',
      'example-input',
      'flex',
      'form',
      'validators',
      'widgets',
    ]);
  });

  it('validates the example form on its own, with no other schema registered', () => {
    const bundle = readJson('src/lib/form.editor.schema.json');
    const validateWithBundle = new Ajv2020({ allErrors: false, strict: false }).compile(bundle);
    const form = readExampleForm() as Record<string, unknown>;
    // The `$schema` key points at this bundle and is allowed by the envelope.
    expect(validateWithBundle(form), JSON.stringify(validateWithBundle.errors, null, 2)).toBe(true);
  });

  it('is what the example form points at', () => {
    expect(readJson('examples/example.form.json')['$schema']).toBe(
      '../src/lib/form.editor.schema.json',
    );
  });
});

describe('regenerating', () => {
  it('is a no-op when nothing changed, which is what the CI staleness check relies on', async () => {
    const before = listFiles(packageRoot).map((file) => [
      file,
      readFileSync(join(packageRoot, file), 'utf-8'),
    ]);
    expect(await runCli(['generate', '--dir', packageRoot])).toBe(0);
    for (const [file, content] of before) {
      expect(readFileSync(join(packageRoot, file as string), 'utf-8'), file as string).toBe(
        content,
      );
    }
  });

  it('refuses to overwrite starter files an implementer may have edited', async () => {
    const errored: string[] = [];
    vi.spyOn(console, 'error').mockImplementation((message) => errored.push(String(message)));
    writeFileSync(join(packageRoot, 'src/lib/validators.schema.json'), '{"edited": true}', 'utf-8');

    const exitCode = await runCli([
      'init',
      '--name',
      'kendo',
      '--id-base',
      ID_BASE,
      '--dir',
      packageRoot,
    ]);

    expect(exitCode).toBe(1);
    expect(errored.join('\n')).toContain('Refusing to overwrite');
    expect(readFileSync(join(packageRoot, 'src/lib/validators.schema.json'), 'utf-8')).toBe(
      '{"edited": true}',
    );
  });
});
