import nx from '@nx/eslint-plugin';
import importPlugin from 'eslint-plugin-import';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: [
      '**/dist',
      '**/.next',
      '**/.nuxt',
      '**/.output',
      '**/.astro',
      '**/vite.config.*.timestamp*',
      '**/vitest.config.*.timestamp*',
      '**/docs/src/examples/**',
      'templates/**',
    ],
  },
  {
    // Generated by Next.js on every dev/build run; its triple-slash
    // references trip @typescript-eslint/triple-slash-reference.
    files: ['**/next-env.d.ts'],
    rules: {
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      // Tags direction
      // ------------------------
      //  scope:app ----> scope:impl -------------> scope:framework ----> scope:core
      //  apps/           gui-shared                react/lit/angular     core
      //  docs/           gui-react/lit/angular     ui-testing            gui-validators
      //                  gui-components/schemas                          dx
      //                  gui-mcp
      //
      // |------------------------------------------------------------------------------------------------|
      // | Tag             | Projects                                                                     |
      // |------------------------------------------------------------------------------------------------|
      // | scope:core      | @golemui/core, @golemui/dx, gui-validators                                   |
      // | scope:framework | @golemui/react/lit/angular/vue, ui-testing                                   |
      // | scope:impl      | gui-shared, gui-react/lit/angular/vue, gui-components, gui-schemas, gui-mcp  |
      // | scope:app       | everything under apps/ and docs/                                             |
      // |------------------------------------------------------------------------------------------------|
      // ( type:app projects cannot import @golemui/*/internals )
      //
      // Notes
      // ------------------------
      // - every scope:impl project also carries an impl:* tag naming its widget set (today: impl:gui).
      //   The impl:* constraint keeps two widget set implementations from importing each other.
      // - ui-testing is tagged scope:framework so any implementation and the apps can import it in tests
      // - apps-shared is intentionally type:lib (not type:app), so the /internals ban does not apply to it
      // ------------------------
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints: [
            { sourceTag: 'type:app', bannedExternalImports: ['@golemui/*/internals'] },
            { sourceTag: 'scope:core', onlyDependOnLibsWithTags: ['scope:core'] },
            {
              sourceTag: 'scope:framework',
              onlyDependOnLibsWithTags: ['scope:core', 'scope:framework'],
            },
            {
              sourceTag: 'scope:impl',
              onlyDependOnLibsWithTags: ['scope:core', 'scope:framework', 'scope:impl'],
            },
            {
              sourceTag: 'impl:gui',
              onlyDependOnLibsWithTags: ['scope:core', 'scope:framework', 'impl:gui'],
            },
            {
              sourceTag: 'scope:app',
              onlyDependOnLibsWithTags: [
                'scope:core',
                'scope:framework',
                'scope:impl',
                'scope:app',
              ],
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    plugins: {
      import: importPlugin,
    },
    // Override or add rules here
    rules: {
      'import/no-namespace': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    // vite/vitest legitimately reference sibling workspace packages by relative path and don't need module-boundary enforcement
    files: ['**/vite.config.*', '**/vitest.config.*'],
    rules: {
      '@nx/enforce-module-boundaries': 'off',
    },
  },
  {
    files: ['**/cypress/support/component.ts'],
    rules: {
      '@nx/enforce-module-boundaries': 'off',
    },
  },
];
