// ─── DX public API — see lib/dx/index.ts for the full list ───

export { gui } from './lib/dx';

export {
  _guiAccordion,
  _guiAlert,
  _guiBooleanInput,
  _guiButton,
  _guiCalendar,
  _guiCheckbox,
  _guiCurrency,
  _guiCustomAction,
  _guiCustomDisplay,
  _guiCustomInput,
  _guiCustomLayout,
  _guiDateInput,
  _guiDatePicker,
  _guiDisplay,
  _guiDropdown,
  _guiFlex,
  _guiGrid,
  _guiHorizontalFlex,
  _guiHorizontalGrid,
  _guiList,
  _guiMarkdown,
  _guiNumberInput,
  _guiPassword,
  _guiRadiogroup,
  _guiRangeCalendar,
  _guiRangeDateInput,
  _guiRangeDatePicker,
  _guiRepeater,
  _guiSelect,
  _guiSubmitButton,
  _guiTabs,
  _guiTextarea,
  _guiTextInput,
  _guiVerticalFlex,
  _guiVerticalGrid,
} from './lib/dx';

export {
  _gslAccordionByUid,
  _gslAccordions,
  _gslActionByUid,
  _gslActions,
  _gslAlertByUid,
  _gslAlerts,
  _gslBooleanInputs,
  _gslCalendarByUid,
  _gslCalendars,
  _gslCheckboxByUid,
  _gslCheckboxes,
  _gslCurrencies,
  _gslCurrencyByUid,
  _gslCustomActionByUid,
  _gslCustomActions,
  _gslCustomDisplayByUid,
  _gslCustomDisplays,
  _gslCustomInputByUid,
  _gslCustomInputs,
  _gslCustomLayoutByUid,
  _gslCustomLayouts,
  _gslDateInputByUid,
  _gslDateInputs,
  _gslDatePickerByUid,
  _gslDatePickers,
  _gslDisplayByUid,
  _gslDisplays,
  _gslDropdownByUid,
  _gslDropdowns,
  _gslInputByUid,
  _gslInputs,
  _gslLayoutByUid,
  _gslLayouts,
  _gslListByUid,
  _gslLists,
  _gslMarkdownByUid,
  _gslMarkdowns,
  _gslNumberInputs,
  _gslPasswordByUid,
  _gslPasswords,
  _gslRadiogroupByUid,
  _gslRadiogroups,
  _gslRangeCalendarByUid,
  _gslRangeCalendars,
  _gslRangeDateInputByUid,
  _gslRangeDateInputs,
  _gslRangeDatePickerByUid,
  _gslRangeDatePickers,
  _gslRepeaterByUid,
  _gslRepeaters,
  _gslSelectByUid,
  _gslSelects,
  _gslStates,
  _gslTabs,
  _gslTabsByUid,
  _gslTag,
  _gslTextareaByUid,
  _gslTextareas,
  _gslTextInputs,
} from './lib/dx';

export {
  createGslSelector,
  defineShortcutType,
  extractWidgetProps,
  formDefs,
  isDxDefinitions,
  processAutoLabel,
  processAutoPlaceholder,
  resolveFormInput,
} from './lib/dx';
export type {
  AccordionDecorator,
  ActionDecorator,
  AlertDecorator,
  BooleanDataInputDecorator,
  CalendarDecorator,
  CheckboxDecorator,
  CurrencyDecorator,
  CustomActionDecorator,
  CustomDisplayDecorator,
  CustomInputDecorator,
  CustomLayoutDecorator,
  DateInputDecorator,
  DatePickerDecorator,
  DefOrCallback,
  DisplayDecorator,
  DropdownDecorator,
  DxActionBase,
  DxCommonFields,
  DxDefinitionItem,
  DxDefinitions,
  DxDisplayBase,
  DxDisplayRenderFn,
  DxFormConfig,
  DxFormEvent,
  DxInputBase,
  DxInternalFields,
  DxLayoutBase,
  DxResult,
  DxRuntimeParams,
  DxValidator,
  FormConfig,
  FormEvents,
  FormInput,
  GslAccordionConfig,
  GslActionsConfig,
  GslAlertsConfig,
  GslCalendarConfig,
  GslCheckboxConfig,
  GslConfigBase,
  GslCurrencyConfig,
  GslCustomActionConfig,
  GslCustomDisplayConfig,
  GslCustomInputConfig,
  GslCustomLayoutConfig,
  GslDateInputConfig,
  GslDatePickerConfig,
  GslDecoratorCallback,
  GslDisplaysConfig,
  GslDropdownConfig,
  GslInputsConfig,
  GslLayoutsConfig,
  GslListConfig,
  GslMarkdownConfig,
  GslPasswordConfig,
  GslRadiogroupConfig,
  GslRangeCalendarConfig,
  GslRangeDateInputConfig,
  GslRangeDatePickerConfig,
  GslRepeaterConfig,
  GslSelectConfig,
  GslSelectorsInput,
  GslTabsConfig,
  GslTextareaConfig,
  GuiFormInitConfig,
  GuiShortcutOf,
  InputDecorator,
  InputTags,
  LayoutDecorator,
  ListDecorator,
  MarkdownDecorator,
  NumberDataInputDecorator,
  PasswordDecorator,
  RadiogroupDecorator,
  RangeCalendarDecorator,
  RangeDateInputDecorator,
  RangeDatePickerDecorator,
  RepeaterDecorator,
  ResolvedFormInput,
  SelectDecorator,
  ShortcutTypeSelectors,
  SimpleFieldDef,
  TabsDecorator,
  TextareaDecorator,
  TextDataInputDecorator,
  ValidShortcutType,
} from './lib/dx';

// ─── golem-form ───

export { golemForm } from './lib/golem-form';

// ─── shared ───

export type { Dependencies } from './lib/shared';

// ─── utils ───

export { isOption } from './lib/utils/one-of';
export { resolveChunkRefs } from './lib/utils/schema';

// ─── widget.props ───

export type {
  AccordionProps,
  AlertProps,
  ButtonProps,
  CalendarProps,
  CheckboxProps,
  ComponentRendererProps,
  CurrencyProps,
  DateinputProps,
  DatePickerProps,
  DateRange,
  DropdownProps,
  FlexProps,
  GridProps,
  ListItem,
  ListProps,
  MarkdownProps,
  MarkdownTextProps,
  NumberinputProps,
  OneOfProps,
  Option,
  OptionValue,
  PasswordProps,
  RadiogroupProps,
  RangeCalendarProps,
  RangeDateInputProps,
  RangeDatePickerProps,
  RendererProps,
  RepeaterProps,
  SelectProps,
  TabsProps,
  TagsProps,
  TagsSeparator,
  TextareaProps,
  TextinputProps,
  ToggleProps,
} from './lib/widget.props';

// ─── widgets ───

export type { GolemWidget } from './lib/widgets';
