// ─── Internals ────────────────────────────────────────────────────────────
//
// Risky / private API. These symbols are NOT part of the stable public surface
// (see `index.ts`). They are exposed only so that other `@golemui/*` libraries
// — framework adapters (react/lit/angular/vue), the renderer component lib, and
// custom-shortcut extensions — can build on top of gui-shared. Importing from
// `@golemui/gui-shared/internals` is a signal that you are reaching into
// internal building blocks; the contract may change without notice.

// ─── DX building blocks: GUI factories (structure) ───
//
// Prefer the `gui` namespace façade (`gui.inputs.textInput(...)`, etc.) — these
// underscore factories are what it wraps.

export {
  _guiAccordion,
  _guiAlert,
  _guiBooleanInput,
  _guiButton,
  _guiCalendar,
  _guiCheckbox,
  _guiCurrency,
  _guiCustomAction,
  _guiCustomDisplay,
  _guiCustomInput,
  _guiCustomLayout,
  _guiDateInput,
  _guiDatePicker,
  _guiDateTimeInput,
  _guiDisplay,
  _guiDropdown,
  _guiFlex,
  _guiGrid,
  _guiHorizontalFlex,
  _guiHorizontalGrid,
  _guiList,
  _guiMarkdown,
  _guiMarkdownText,
  _guiNumberInput,
  _guiPassword,
  _guiRadiogroup,
  _guiRangeCalendar,
  _guiRangeDateInput,
  _guiRangeDatePicker,
  _guiRepeater,
  _guiSelect,
  _guiTabs,
  _guiTags,
  _guiTextarea,
  _guiTextInput,
  _guiTimeInput,
  _guiVerticalFlex,
  _guiVerticalGrid,
} from './lib/dx';

// ─── DX building blocks: GSL selectors (behavior) ───
//
// Prefer the `gui.selectors` chain — these underscore selectors are what it wraps.

export {
  _gslAccordionByUid,
  _gslAccordions,
  _gslActionByUid,
  _gslActions,
  _gslAlertByUid,
  _gslAlerts,
  _gslBooleanInputs,
  _gslCalendarByUid,
  _gslCalendars,
  _gslCheckboxByUid,
  _gslCheckboxes,
  _gslCurrencies,
  _gslCurrencyByUid,
  _gslCustomActionByUid,
  _gslCustomActions,
  _gslCustomDisplayByUid,
  _gslCustomDisplays,
  _gslCustomInputByUid,
  _gslCustomInputs,
  _gslCustomLayoutByUid,
  _gslCustomLayouts,
  _gslDateInputByUid,
  _gslDateInputs,
  _gslDatePickerByUid,
  _gslDatePickers,
  _gslDateTimeInputByUid,
  _gslDateTimeInputs,
  _gslDisplayByUid,
  _gslDisplays,
  _gslDropdownByUid,
  _gslDropdowns,
  _gslInputByUid,
  _gslInputs,
  _gslLayoutByUid,
  _gslLayouts,
  _gslListByUid,
  _gslLists,
  _gslMarkdownByUid,
  _gslMarkdowns,
  _gslMarkdownTextByUid,
  _gslMarkdownTexts,
  _gslNumberInputs,
  _gslPasswordByUid,
  _gslPasswords,
  _gslRadiogroupByUid,
  _gslRadiogroups,
  _gslRangeCalendarByUid,
  _gslRangeCalendars,
  _gslRangeDateInputByUid,
  _gslRangeDateInputs,
  _gslRangeDatePickerByUid,
  _gslRangeDatePickers,
  _gslRepeaterByUid,
  _gslRepeaters,
  _gslSelectByUid,
  _gslSelects,
  _gslStates,
  _gslTabs,
  _gslTabsByUid,
  _gslTag,
  _gslTags,
  _gslTagsByUid,
  _gslTextareaByUid,
  _gslTextareas,
  _gslTextInputs,
  _gslTimeInputByUid,
  _gslTimeInputs,
} from './lib/dx';

// ─── DX pipeline / extension API ───

export {
  createGslSelector,
  defineShortcutType,
  extractWidgetProps,
  formDefs,
  isDxDefinitions,
  processAutoLabel,
  processAutoPlaceholder,
  resolveFormInput,
} from './lib/dx';

// ─── DX types (decorators, configs, base/extension types) ───

export type {
  AccordionDecorator,
  ActionDecorator,
  AlertDecorator,
  BooleanDataInputDecorator,
  CalendarDecorator,
  CheckboxDecorator,
  CurrencyDecorator,
  CustomActionDecorator,
  CustomDisplayDecorator,
  CustomInputDecorator,
  CustomLayoutDecorator,
  DateInputDecorator,
  DatePickerDecorator,
  DateTimeInputDecorator,
  DefOrCallback,
  DisplayDecorator,
  DropdownDecorator,
  DxActionBase,
  DxCommonFields,
  DxDisplayBase,
  DxDisplayRenderFn,
  DxFormEvent,
  DxInputBase,
  DxInternalFields,
  DxLayoutBase,
  DxResult,
  DxRuntimeParams,
  DxValidator,
  FormConfig,
  FormEvents,
  FormInput,
  GslAccordionConfig,
  GslActionsConfig,
  GslAlertsConfig,
  GslCalendarConfig,
  GslCheckboxConfig,
  GslConfigBase,
  GslCurrencyConfig,
  GslCustomActionConfig,
  GslCustomDisplayConfig,
  GslCustomInputConfig,
  GslCustomLayoutConfig,
  GslDateInputConfig,
  GslDatePickerConfig,
  GslDateTimeInputConfig,
  GslDecoratorCallback,
  GslDisplaysConfig,
  GslDropdownConfig,
  GslInputsConfig,
  GslLayoutsConfig,
  GslListConfig,
  GslMarkdownConfig,
  GslPasswordConfig,
  GslRadiogroupConfig,
  GslRangeCalendarConfig,
  GslRangeDateInputConfig,
  GslRangeDatePickerConfig,
  GslRepeaterConfig,
  GslSelectConfig,
  GslTabsConfig,
  GslTagsConfig,
  GslTextareaConfig,
  GslTimeInputConfig,
  GuiShortcutOf,
  InputDecorator,
  InputTags,
  LayoutDecorator,
  ListDecorator,
  MarkdownDecorator,
  NumberDataInputDecorator,
  PasswordDecorator,
  RadiogroupDecorator,
  RangeCalendarDecorator,
  RangeDateInputDecorator,
  RangeDatePickerDecorator,
  RepeaterDecorator,
  ResolvedFormInput,
  SelectDecorator,
  ShortcutTypeSelectors,
  SimpleFieldDef,
  TabsDecorator,
  TagsDecorator,
  TextareaDecorator,
  TextDataInputDecorator,
  TimeInputDecorator,
  ValidShortcutType,
} from './lib/dx';

// ─── Widget contract types (consumed by framework adapters / renderers) ───

export type {
  AccordionProps,
  AlertProps,
  ButtonProps,
  CalendarProps,
  CheckboxProps,
  ComponentRendererProps,
  CurrencyProps,
  DateinputProps,
  DatePickerProps,
  DateTimeInputProps,
  DateRange,
  DropdownProps,
  FlexProps,
  GridProps,
  ListItem,
  ListProps,
  MarkdownProps,
  MarkdownTextProps,
  NumberinputProps,
  OneOfProps,
  Option,
  OptionValue,
  PasswordProps,
  RadiogroupProps,
  RangeCalendarProps,
  RangeDateInputProps,
  RangeDatePickerProps,
  RendererProps,
  RepeaterProps,
  SelectProps,
  TabsProps,
  TagsProps,
  TagsSeparator,
  TextareaProps,
  TextinputProps,
  TimeInputProps,
  ToggleProps,
} from './lib/widget.props';

export type { GolemWidget } from './lib/widgets';

// ─── golem-form (JSON form builder — currently used only by test libs) ───

export { golemForm } from './lib/golem-form';

// ─── Utils ───

export { isOption } from './lib/utils/one-of';
export { getItemKey } from './lib/utils/repeater';
