import { describe, expect, it } from 'vitest';
import { gui, resolveChunkRefs } from './index';
import {
  // ─── GUI factories (structure) ───
  _guiAccordion,
  _guiAlert,
  _guiBooleanInput,
  _guiButton,
  _guiCalendar,
  _guiDateTimeCalendar,
  _guiDateTimePicker,
  _guiCheckbox,
  _guiCurrency,
  _guiCustomAction,
  _guiCustomDisplay,
  _guiCustomInput,
  _guiCustomLayout,
  _guiDateInput,
  _guiDatePicker,
  _guiDateTimeInput,
  _guiDisplay,
  _guiDropdown,
  _guiFlex,
  _guiGrid,
  _guiHorizontalFlex,
  _guiHorizontalGrid,
  _guiList,
  _guiMarkdown,
  _guiMarkdownText,
  _guiNumberInput,
  _guiPassword,
  _guiRadiogroup,
  _guiRangeCalendar,
  _guiRangeDateInput,
  _guiRangeDateTimeInput,
  _guiRangeDateTimeCalendar,
  _guiRangeDateTimePicker,
  _guiRangeTimeInput,
  _guiRangeDatePicker,
  _guiRangeTimePicker,
  _guiRepeater,
  _guiSelect,
  _guiTabs,
  _guiTags,
  _guiTextarea,
  _guiTextInput,
  _guiTimeInput,
  _guiTimePicker,
  _guiVerticalFlex,
  _guiVerticalGrid,
  // ─── GSL selectors (behavior) ───
  _gslAccordionByUid,
  _gslAccordions,
  _gslActionByUid,
  _gslActions,
  _gslAlertByUid,
  _gslAlerts,
  _gslBooleanInputs,
  _gslCalendarByUid,
  _gslCalendars,
  _gslDateTimeCalendarByUid,
  _gslDateTimeCalendars,
  _gslCheckboxByUid,
  _gslCheckboxes,
  _gslCurrencies,
  _gslCurrencyByUid,
  _gslCustomActionByUid,
  _gslCustomActions,
  _gslCustomDisplayByUid,
  _gslCustomDisplays,
  _gslCustomInputByUid,
  _gslCustomInputs,
  _gslCustomLayoutByUid,
  _gslCustomLayouts,
  _gslDateInputByUid,
  _gslDateInputs,
  _gslDatePickerByUid,
  _gslDatePickers,
  _gslDateTimePickerByUid,
  _gslDateTimePickers,
  _gslDateTimeInputByUid,
  _gslDateTimeInputs,
  _gslDisplayByUid,
  _gslDisplays,
  _gslDropdownByUid,
  _gslDropdowns,
  _gslInputByUid,
  _gslInputs,
  _gslLayoutByUid,
  _gslLayouts,
  _gslListByUid,
  _gslLists,
  _gslMarkdownByUid,
  _gslMarkdowns,
  _gslMarkdownTextByUid,
  _gslMarkdownTexts,
  _gslNumberInputs,
  _gslPasswordByUid,
  _gslPasswords,
  _gslRadiogroupByUid,
  _gslRadiogroups,
  _gslRangeCalendarByUid,
  _gslRangeCalendars,
  _gslRangeDateInputByUid,
  _gslRangeDateInputs,
  _gslRangeDateTimeInputByUid,
  _gslRangeDateTimeInputs,
  _gslRangeDateTimeCalendarByUid,
  _gslRangeDateTimeCalendars,
  _gslRangeDateTimePickerByUid,
  _gslRangeDateTimePickers,
  _gslRangeTimeInputByUid,
  _gslRangeTimeInputs,
  _gslRangeDatePickerByUid,
  _gslRangeDatePickers,
  _gslRangeTimePickerByUid,
  _gslRangeTimePickers,
  _gslRepeaterByUid,
  _gslRepeaters,
  _gslSelectByUid,
  _gslSelects,
  _gslStates,
  _gslTabs,
  _gslTabsByUid,
  _gslTag,
  _gslTags,
  _gslTagsByUid,
  _gslTextareaByUid,
  _gslTextareas,
  _gslTextInputs,
  _gslTimeInputByUid,
  _gslTimeInputs,
  _gslTimePickerByUid,
  _gslTimePickers,
  // ─── DX pipeline / extension API ───
  createGslSelector,
  defineShortcutType,
  extractWidgetProps,
  formDefs,
  isDxDefinitions,
  processAutoLabel,
  processAutoPlaceholder,
  resolveFormInput,
  // ─── golem-form and utils ───
  golemForm,
  isOption,
  getItemKey,
} from './internals';

// Pins the package entry surface as it existed before the DX pipeline moved to
// `@golemui/dx`. Every name below was importable from `@golemui/gui-shared` or
// `@golemui/gui-shared/internals` before the move and must stay importable
// forever — the compatibility re-exports are a permanent part of the API.
//
// A dropped value export fails this file at module-link time (the named import
// above no longer resolves); the runtime assertions below give a readable
// per-name report on top. Type exports are covered by the `import type` blocks
// at the bottom, which fail the vitest typecheck pass configured in
// vite.config.ts (`test.typecheck`, using tsconfig.legacy-imports.json) when a
// type re-export is dropped.

const publicValueExports = { gui, resolveChunkRefs };

const internalsValueExports = {
  _guiAccordion,
  _guiAlert,
  _guiBooleanInput,
  _guiButton,
  _guiCalendar,
  _guiDateTimeCalendar,
  _guiDateTimePicker,
  _guiCheckbox,
  _guiCurrency,
  _guiCustomAction,
  _guiCustomDisplay,
  _guiCustomInput,
  _guiCustomLayout,
  _guiDateInput,
  _guiDatePicker,
  _guiDateTimeInput,
  _guiDisplay,
  _guiDropdown,
  _guiFlex,
  _guiGrid,
  _guiHorizontalFlex,
  _guiHorizontalGrid,
  _guiList,
  _guiMarkdown,
  _guiMarkdownText,
  _guiNumberInput,
  _guiPassword,
  _guiRadiogroup,
  _guiRangeCalendar,
  _guiRangeDateInput,
  _guiRangeDateTimeInput,
  _guiRangeDateTimeCalendar,
  _guiRangeDateTimePicker,
  _guiRangeTimeInput,
  _guiRangeDatePicker,
  _guiRangeTimePicker,
  _guiRepeater,
  _guiSelect,
  _guiTabs,
  _guiTags,
  _guiTextarea,
  _guiTextInput,
  _guiTimeInput,
  _guiTimePicker,
  _guiVerticalFlex,
  _guiVerticalGrid,
  _gslAccordionByUid,
  _gslAccordions,
  _gslActionByUid,
  _gslActions,
  _gslAlertByUid,
  _gslAlerts,
  _gslBooleanInputs,
  _gslCalendarByUid,
  _gslCalendars,
  _gslDateTimeCalendarByUid,
  _gslDateTimeCalendars,
  _gslCheckboxByUid,
  _gslCheckboxes,
  _gslCurrencies,
  _gslCurrencyByUid,
  _gslCustomActionByUid,
  _gslCustomActions,
  _gslCustomDisplayByUid,
  _gslCustomDisplays,
  _gslCustomInputByUid,
  _gslCustomInputs,
  _gslCustomLayoutByUid,
  _gslCustomLayouts,
  _gslDateInputByUid,
  _gslDateInputs,
  _gslDatePickerByUid,
  _gslDatePickers,
  _gslDateTimePickerByUid,
  _gslDateTimePickers,
  _gslDateTimeInputByUid,
  _gslDateTimeInputs,
  _gslDisplayByUid,
  _gslDisplays,
  _gslDropdownByUid,
  _gslDropdowns,
  _gslInputByUid,
  _gslInputs,
  _gslLayoutByUid,
  _gslLayouts,
  _gslListByUid,
  _gslLists,
  _gslMarkdownByUid,
  _gslMarkdowns,
  _gslMarkdownTextByUid,
  _gslMarkdownTexts,
  _gslNumberInputs,
  _gslPasswordByUid,
  _gslPasswords,
  _gslRadiogroupByUid,
  _gslRadiogroups,
  _gslRangeCalendarByUid,
  _gslRangeCalendars,
  _gslRangeDateInputByUid,
  _gslRangeDateInputs,
  _gslRangeDateTimeInputByUid,
  _gslRangeDateTimeInputs,
  _gslRangeDateTimeCalendarByUid,
  _gslRangeDateTimeCalendars,
  _gslRangeDateTimePickerByUid,
  _gslRangeDateTimePickers,
  _gslRangeTimeInputByUid,
  _gslRangeTimeInputs,
  _gslRangeDatePickerByUid,
  _gslRangeDatePickers,
  _gslRangeTimePickerByUid,
  _gslRangeTimePickers,
  _gslRepeaterByUid,
  _gslRepeaters,
  _gslSelectByUid,
  _gslSelects,
  _gslStates,
  _gslTabs,
  _gslTabsByUid,
  _gslTag,
  _gslTags,
  _gslTagsByUid,
  _gslTextareaByUid,
  _gslTextareas,
  _gslTextInputs,
  _gslTimeInputByUid,
  _gslTimeInputs,
  _gslTimePickerByUid,
  _gslTimePickers,
  createGslSelector,
  defineShortcutType,
  extractWidgetProps,
  formDefs,
  isDxDefinitions,
  processAutoLabel,
  processAutoPlaceholder,
  resolveFormInput,
  golemForm,
  isOption,
  getItemKey,
};

describe('legacy import surface', () => {
  it('keeps every pre-move public value export', () => {
    for (const [name, value] of Object.entries(publicValueExports)) {
      expect(value, name).toBeDefined();
    }
  });

  it('keeps every pre-move internals value export', () => {
    for (const [name, value] of Object.entries(internalsValueExports)) {
      expect(value, name).toBeDefined();
    }
  });

  it('keeps the gui namespace shape', () => {
    expect(typeof gui.inputs.textInput).toBe('function');
    expect(typeof gui.actions.button).toBe('function');
    expect(typeof gui.displays.display).toBe('function');
    expect(typeof gui.layouts.flex).toBe('function');
    expect(typeof gui.selectors.tag).toBe('function');
  });

  it('still resolves a minimal gui form end to end', () => {
    const resolved = resolveFormInput([gui.inputs.textInput('name')]);
    expect(resolved.formDef).toBeDefined();
    const rootWidget = (resolved.formDef as { form?: { kind?: string; type?: string } }).form;
    expect(rootWidget?.kind).toBe('layout');
    expect(rootWidget?.type).toBe('flex');
  });
});

// ─── Type exports (compile-time coverage) ─────────────────────────────────
// A dropped type re-export breaks these imports under the vitest typecheck
// pass (see `test.typecheck` in vite.config.ts), which CI runs as part of
// the vite:test target.

import type {
  DxDefinitionItem as _T1,
  DxDefinitions as _T2,
  DxFormConfig as _T3,
  GslSelectorsInput as _T4,
  GuiFormInitConfig as _T5,
  Dependencies as _T6,
  ExpressionFunction as _T7,
  ExpressionFunctions as _T8,
} from './index';

import type {
  AccordionDecorator,
  ActionDecorator,
  AlertDecorator,
  BooleanDataInputDecorator,
  CalendarDecorator,
  DateTimeCalendarDecorator,
  GslDateTimeCalendarConfig,
  CheckboxDecorator,
  CurrencyDecorator,
  CustomActionDecorator,
  CustomDisplayDecorator,
  CustomInputDecorator,
  CustomLayoutDecorator,
  DateInputDecorator,
  DatePickerDecorator,
  DateTimePickerDecorator,
  DateTimeInputDecorator,
  DefOrCallback,
  DisplayDecorator,
  DropdownDecorator,
  DxActionBase,
  DxCommonFields,
  DxDisplayBase,
  DxDisplayRenderFn,
  DxFormEvent,
  DxInputBase,
  DxInternalFields,
  DxLayoutBase,
  DxResult,
  DxRuntimeParams,
  DxValidator,
  FormConfig,
  FormEvents,
  FormInput,
  GslAccordionConfig,
  GslActionsConfig,
  GslAlertsConfig,
  GslCalendarConfig,
  GslCheckboxConfig,
  GslConfigBase,
  GslCurrencyConfig,
  GslCustomActionConfig,
  GslCustomDisplayConfig,
  GslCustomInputConfig,
  GslCustomLayoutConfig,
  GslDateInputConfig,
  GslDatePickerConfig,
  GslDateTimePickerConfig,
  GslDateTimeInputConfig,
  GslDecoratorCallback,
  GslDisplaysConfig,
  GslDropdownConfig,
  GslInputsConfig,
  GslLayoutsConfig,
  GslListConfig,
  GslMarkdownConfig,
  GslPasswordConfig,
  GslRadiogroupConfig,
  GslRangeCalendarConfig,
  GslRangeDateInputConfig,
  GslRangeDateTimeInputConfig,
  GslRangeDateTimeCalendarConfig,
  GslRangeDateTimePickerConfig,
  GslRangeTimeInputConfig,
  GslRangeDatePickerConfig,
  GslRangeTimePickerConfig,
  GslRepeaterConfig,
  GslSelectConfig,
  GslTabsConfig,
  GslTagsConfig,
  GslTextareaConfig,
  GslTimeInputConfig,
  GslTimePickerConfig,
  GuiShortcutOf,
  InputDecorator,
  InputTags,
  LayoutDecorator,
  ListDecorator,
  MarkdownDecorator,
  NumberDataInputDecorator,
  PasswordDecorator,
  RadiogroupDecorator,
  RangeCalendarDecorator,
  RangeDateInputDecorator,
  RangeDateTimeInputDecorator,
  RangeDateTimeCalendarDecorator,
  RangeDateTimePickerDecorator,
  RangeTimeInputDecorator,
  RangeDatePickerDecorator,
  RangeTimePickerDecorator,
  RepeaterDecorator,
  ResolvedFormInput,
  SelectDecorator,
  ShortcutTypeSelectors,
  SimpleFieldDef,
  TabsDecorator,
  TagsDecorator,
  TextareaDecorator,
  TextDataInputDecorator,
  TimeInputDecorator,
  TimePickerDecorator,
  ValidShortcutType,
} from './internals';

import type {
  AccordionProps,
  AlertProps,
  ButtonProps,
  CalendarProps,
  DateTimeCalendarProps,
  DateTimePickerProps,
  CheckboxProps,
  ComponentRendererProps,
  CurrencyProps,
  DateinputProps,
  DatePickerProps,
  DateTimeInputProps,
  DateRange,
  DateTimeRange,
  DisabledTimeRange,
  DropdownProps,
  FlexProps,
  GridProps,
  ListItem,
  ListProps,
  MarkdownProps,
  MarkdownTextProps,
  NumberinputProps,
  OneOfProps,
  Option,
  OptionValue,
  PasswordProps,
  RadiogroupProps,
  RangeCalendarProps,
  RangeDateInputProps,
  RangeDatePickerProps,
  RangeDateTimeInputProps,
  RangeDateTimeCalendarProps,
  RangeDateTimePickerProps,
  RangeTimeInputProps,
  RangeTimePickerProps,
  RendererProps,
  RepeaterProps,
  SelectProps,
  TabsProps,
  TagsProps,
  TagsSeparator,
  TextareaProps,
  TextinputProps,
  TimeInputProps,
  TimePickerProps,
  TimeRange,
  ToggleProps,
  GolemWidget,
} from './internals';

// Reference every imported type once, so none of the imports above can be
// flagged as unused. Exporting the tuple marks it as used as well.
export type LegacyPublicTypeSurface = [_T1, _T2, _T3, _T4, _T5, _T6, _T7, _T8];
export type LegacyInternalsTypeSurface = [
  AccordionDecorator,
  ActionDecorator,
  AlertDecorator,
  BooleanDataInputDecorator,
  CalendarDecorator,
  DateTimeCalendarDecorator,
  GslDateTimeCalendarConfig,
  CheckboxDecorator,
  CurrencyDecorator,
  CustomActionDecorator,
  CustomDisplayDecorator,
  CustomInputDecorator,
  CustomLayoutDecorator,
  DateInputDecorator,
  DatePickerDecorator,
  DateTimePickerDecorator,
  DateTimeInputDecorator,
  DefOrCallback<unknown>,
  DisplayDecorator,
  DropdownDecorator,
  DxActionBase,
  DxCommonFields,
  DxDisplayBase,
  DxDisplayRenderFn,
  DxFormEvent,
  DxInputBase,
  DxInternalFields,
  DxLayoutBase,
  DxResult,
  DxRuntimeParams,
  DxValidator<{ type: 'string' }>,
  FormConfig,
  FormEvents,
  FormInput,
  GslAccordionConfig,
  GslActionsConfig,
  GslAlertsConfig,
  GslCalendarConfig,
  GslCheckboxConfig,
  GslConfigBase<unknown>,
  GslCurrencyConfig,
  GslCustomActionConfig,
  GslCustomDisplayConfig,
  GslCustomInputConfig,
  GslCustomLayoutConfig,
  GslDateInputConfig,
  GslDatePickerConfig,
  GslDateTimePickerConfig,
  GslDateTimeInputConfig,
  GslDecoratorCallback<unknown>,
  GslDisplaysConfig,
  GslDropdownConfig,
  GslInputsConfig,
  GslLayoutsConfig,
  GslListConfig,
  GslMarkdownConfig,
  GslPasswordConfig,
  GslRadiogroupConfig,
  GslRangeCalendarConfig,
  GslRangeDateInputConfig,
  GslRangeDateTimeInputConfig,
  GslRangeDateTimeCalendarConfig,
  GslRangeDateTimePickerConfig,
  GslRangeTimeInputConfig,
  GslRangeDatePickerConfig,
  GslRangeTimePickerConfig,
  GslRepeaterConfig,
  GslSelectConfig,
  GslTabsConfig,
  GslTagsConfig,
  GslTextareaConfig,
  GslTimeInputConfig,
  GslTimePickerConfig,
  GuiShortcutOf<string, unknown>,
  InputDecorator,
  InputTags,
  LayoutDecorator,
  ListDecorator,
  MarkdownDecorator,
  NumberDataInputDecorator,
  PasswordDecorator,
  RadiogroupDecorator,
  RangeCalendarDecorator,
  RangeDateInputDecorator,
  RangeDateTimeInputDecorator,
  RangeDateTimeCalendarDecorator,
  RangeDateTimePickerDecorator,
  RangeTimeInputDecorator,
  RangeDatePickerDecorator,
  RangeTimePickerDecorator,
  RepeaterDecorator,
  ResolvedFormInput,
  SelectDecorator,
  ShortcutTypeSelectors<DxCommonFields, GslConfigBase<DxCommonFields>>,
  SimpleFieldDef,
  TabsDecorator,
  TagsDecorator,
  TextareaDecorator,
  TextDataInputDecorator,
  TimeInputDecorator,
  TimePickerDecorator,
  ValidShortcutType,
];
export type LegacyWidgetPropsTypeSurface = [
  AccordionProps,
  AlertProps,
  ButtonProps,
  CalendarProps,
  DateTimeCalendarProps,
  DateTimePickerProps,
  CheckboxProps,
  ComponentRendererProps,
  CurrencyProps,
  DateinputProps,
  DatePickerProps,
  DateTimeInputProps,
  DateRange,
  DateTimeRange,
  DisabledTimeRange,
  DropdownProps<any>,
  FlexProps,
  GridProps,
  ListItem<any>,
  ListProps<any>,
  MarkdownProps,
  MarkdownTextProps,
  NumberinputProps,
  OneOfProps,
  Option,
  OptionValue,
  PasswordProps,
  RadiogroupProps,
  RangeCalendarProps,
  RangeDateInputProps,
  RangeDatePickerProps,
  RangeDateTimeInputProps,
  RangeDateTimeCalendarProps,
  RangeDateTimePickerProps,
  RangeTimeInputProps,
  RangeTimePickerProps,
  RendererProps,
  RepeaterProps<any>,
  SelectProps,
  TabsProps,
  TagsProps,
  TagsSeparator,
  TextareaProps,
  TextinputProps,
  TimeInputProps,
  TimePickerProps,
  TimeRange,
  ToggleProps,
  GolemWidget,
];

// --- Dependency shape (compile-time coverage) -----------------------------
// `@golemui/dx` declares the dependency-carrying types generic over the
// dependency shape, defaulted to an open record, so a second widget set can
// bring its own keys. gui-shared binds them to the gui `Dependencies` (see
// `lib/dx/guiDependencyTypes.ts`). These probes fail the typecheck pass if
// that binding is ever lost: reading a documented key must keep compiling,
// and a wrong dependency value must keep failing.

import type { DxFormConfig as GuiDxFormConfig, GuiFormInitConfig as GuiInitConfig } from './index';

/**
 * Never called. Its body is the assertion: every read path that compiled
 * before `@golemui/dx` was extracted must still compile.
 */
export function legacyDependencyReadProbes(
  resolved: ResolvedFormInput,
  result: DxResult,
  resolve: typeof resolveFormInput,
  service: typeof formDefs,
): (string | undefined)[] {
  return [
    resolved.dependencies?.markdown?.parse('# heading'),
    result.dependencies?.markdown?.parse('# heading'),
    resolve([]).dependencies?.markdown?.parse('# heading'),
    service.processDxFacade([]).dependencies?.markdown?.parse('# heading'),
  ];
}

export const legacyFormConfigDependencyProbe: FormConfig = {
  dependencies: {
    markdown: {
      // @ts-expect-error the gui markdown dependency must declare a parse function
      parse: 42,
    },
  },
};

export const legacyDxFormConfigDependencyProbe: GuiDxFormConfig = {
  dependencies: {
    markdown: {
      // @ts-expect-error the gui markdown dependency must declare a parse function
      parse: 42,
    },
  },
};

export const legacyInitConfigDependencyProbe: GuiInitConfig = {
  formDef: [],
  dependencies: {
    markdown: {
      // @ts-expect-error the gui markdown dependency must declare a parse function
      parse: 42,
    },
  },
  formConfig: {
    dependencies: {
      markdown: {
        // @ts-expect-error the gui markdown dependency must declare a parse function
        parse: 42,
      },
    },
  },
};
