// Pins the gui selector chain surface (`gui.selectors`, generated by
// `createSelectors` from the flat factory map in gui.ts):
//
//   1. the exact method set and each method's emitted selectorType, so a
//      miswired or dropped map entry fails here instead of failing a user,
//   2. the scope method semantics (tag/state/tagsAnd/tagsOr) that the
//      hand-written ScopeChain class implemented before the swap.
//
// The one-time proof that the generated chain was method-for-method
// equivalent to the deleted ScopeChain class ran as scopeChainParity.spec.ts
// on the branch that made the swap.
import { describe, expect, it } from 'vitest';
import { gui } from '../gui';

const SCOPE_METHOD_NAMES = ['tag', 'state', 'tagsAnd', 'tagsOr'];

// method name -> selectorType of the emitted leaf. This is the full selector
// surface of the gui chain; update it deliberately when adding a widget type.
const SELECTOR_TYPE_BY_METHOD: Record<string, string> = {
  inputs: 'INPUTS',
  inputByUid: 'INPUTS',
  textInputs: 'INPUTS',
  numberInputs: 'INPUTS',
  booleanInputs: 'INPUTS',
  selects: 'SELECT',
  selectByUid: 'SELECT',
  dropdowns: 'DROPDOWN',
  dropdownByUid: 'DROPDOWN',
  radiogroups: 'RADIOGROUP',
  radiogroupByUid: 'RADIOGROUP',
  checkboxes: 'CHECKBOX',
  checkboxByUid: 'CHECKBOX',
  textareas: 'TEXTAREA',
  textareaByUid: 'TEXTAREA',
  passwords: 'PASSWORD',
  passwordByUid: 'PASSWORD',
  currencies: 'CURRENCY',
  currencyByUid: 'CURRENCY',
  markdowns: 'MARKDOWN',
  markdownByUid: 'MARKDOWN',
  lists: 'LIST',
  listByUid: 'LIST',
  multiDropdowns: 'MULTI_DROPDOWN',
  multiDropdownByUid: 'MULTI_DROPDOWN',
  multiLists: 'MULTI_LIST',
  multiListByUid: 'MULTI_LIST',
  calendars: 'CALENDAR',
  calendarByUid: 'CALENDAR',
  dateTimeCalendars: 'DATE_TIME_CALENDAR',
  dateTimeCalendarByUid: 'DATE_TIME_CALENDAR',
  dateInputs: 'DATE_INPUT',
  dateInputByUid: 'DATE_INPUT',
  timeInputs: 'TIME_INPUT',
  timeInputByUid: 'TIME_INPUT',
  timePickers: 'TIME_PICKER',
  timePickerByUid: 'TIME_PICKER',
  dateTimeInputs: 'DATE_TIME_INPUT',
  dateTimeInputByUid: 'DATE_TIME_INPUT',
  datePickers: 'DATE_PICKER',
  datePickerByUid: 'DATE_PICKER',
  dateTimePickers: 'DATE_TIME_PICKER',
  dateTimePickerByUid: 'DATE_TIME_PICKER',
  rangeCalendars: 'RANGE_CALENDAR',
  rangeCalendarByUid: 'RANGE_CALENDAR',
  rangeDateInputs: 'RANGE_DATE_INPUT',
  rangeDateInputByUid: 'RANGE_DATE_INPUT',
  rangeTimeInputs: 'RANGE_TIME_INPUT',
  rangeTimeInputByUid: 'RANGE_TIME_INPUT',
  rangeDateTimeInputs: 'RANGE_DATE_TIME_INPUT',
  rangeDateTimeInputByUid: 'RANGE_DATE_TIME_INPUT',
  rangeDateTimeCalendars: 'RANGE_DATE_TIME_CALENDAR',
  rangeDateTimeCalendarByUid: 'RANGE_DATE_TIME_CALENDAR',
  rangeDateTimePickers: 'RANGE_DATE_TIME_PICKER',
  rangeDateTimePickerByUid: 'RANGE_DATE_TIME_PICKER',
  rangeDatePickers: 'RANGE_DATE_PICKER',
  rangeDatePickerByUid: 'RANGE_DATE_PICKER',
  rangeTimePickers: 'RANGE_TIME_PICKER',
  rangeTimePickerByUid: 'RANGE_TIME_PICKER',
  repeaters: 'REPEATER',
  repeaterByUid: 'REPEATER',
  actions: 'ACTIONS',
  actionByUid: 'ACTIONS',
  layouts: 'LAYOUTS',
  layoutByUid: 'LAYOUTS',
  displays: 'DISPLAYS',
  displayByUid: 'DISPLAYS',
  alerts: 'ALERTS',
  alertByUid: 'ALERTS',
  markdownTexts: 'MARKDOWN_TEXTS',
  markdownTextByUid: 'MARKDOWN_TEXTS',
  tabs: 'TABS',
  tabsByUid: 'TABS',
  accordions: 'ACCORDION',
  accordionByUid: 'ACCORDION',
  customInputs: 'CUSTOM_INPUT',
  customInputByUid: 'CUSTOM_INPUT',
  customActions: 'CUSTOM_ACTION',
  customActionByUid: 'CUSTOM_ACTION',
  customDisplays: 'CUSTOM_DISPLAY',
  customDisplayByUid: 'CUSTOM_DISPLAY',
  customLayouts: 'CUSTOM_LAYOUT',
  customLayoutByUid: 'CUSTOM_LAYOUT',
};

function buildLeaf(chain: any, methodName: string, config: Record<string, unknown> = {}) {
  if (methodName.endsWith('ByUid')) {
    return chain[methodName]('probe-uid', config);
  }
  return chain[methodName](config);
}

describe('gui.selectors method surface', () => {
  it('exposes exactly the pinned method set', () => {
    const expectedNames = [...Object.keys(SELECTOR_TYPE_BY_METHOD), ...SCOPE_METHOD_NAMES].sort();
    expect(Object.keys(gui.selectors).sort()).toEqual(expectedNames);
  });

  it('every method emits a leaf with the pinned selectorType and the given config', () => {
    for (const [methodName, selectorType] of Object.entries(SELECTOR_TYPE_BY_METHOD)) {
      const config = { override: { label: 'probe' } };
      const leaf = buildLeaf(gui.selectors, methodName, config);
      expect(leaf.kind, methodName).toBe('leaf');
      expect(leaf.selectorType, methodName).toBe(selectorType);
      expect(leaf.config, methodName).toBe(config);
      expect(leaf.targetState, methodName).toBeUndefined();
    }
  });

  it('ByUid methods match only the given uid', () => {
    const byUidNames = Object.keys(SELECTOR_TYPE_BY_METHOD).filter((name) =>
      name.endsWith('ByUid'),
    );
    expect(byUidNames.length).toBe(39 + 1); // 39 widget pairs plus inputByUid
    for (const methodName of byUidNames) {
      const leaf = buildLeaf(gui.selectors, methodName);
      expect(leaf.matcher({ uid: 'probe-uid' }), methodName).toBe(true);
      expect(leaf.matcher({ uid: 'other-uid' }), methodName).toBe(false);
    }
  });

  it('the input subtype selectors match on the decorator type', () => {
    expect(gui.selectors.textInputs({}).matcher({ type: 'text' })).toBe(true);
    expect(gui.selectors.textInputs({}).matcher({ type: 'number' })).toBe(false);
    expect(gui.selectors.numberInputs({}).matcher({ type: 'number' })).toBe(true);
    expect(gui.selectors.numberInputs({}).matcher({ type: 'boolean' })).toBe(false);
    expect(gui.selectors.booleanInputs({}).matcher({ type: 'boolean' })).toBe(true);
    expect(gui.selectors.booleanInputs({}).matcher({ type: 'text' })).toBe(false);
  });
});

describe('gui.selectors scope methods', () => {
  it('tag narrows the matcher to widgets carrying the tag', () => {
    const leaf = gui.selectors.tag('billing').inputs({});
    expect(leaf.matcher({ tags: ['billing'] })).toBe(true);
    expect(leaf.matcher({ tags: ['admin'] })).toBe(false);
    expect(leaf.matcher({ tags: [] })).toBe(false);
    expect(leaf.matcher({})).toBe(false);
  });

  it('stacked tag calls require every tag', () => {
    const leaf = gui.selectors.tag('billing').tag('admin').inputs({});
    expect(leaf.matcher({ tags: ['billing', 'admin'] })).toBe(true);
    expect(leaf.matcher({ tags: ['billing'] })).toBe(false);
  });

  it('tagsAnd requires all of the given tags', () => {
    const leaf = gui.selectors.tagsAnd(['billing', 'admin']).inputs({});
    expect(leaf.matcher({ tags: ['billing', 'admin', 'extra'] })).toBe(true);
    expect(leaf.matcher({ tags: ['admin'] })).toBe(false);
  });

  it('tagsOr requires at least one of the given tags, and an empty list is a no-op', () => {
    const leaf = gui.selectors.tagsOr(['billing', 'missing']).inputs({});
    expect(leaf.matcher({ tags: ['billing'] })).toBe(true);
    expect(leaf.matcher({ tags: ['other'] })).toBe(false);

    const emptyOr = gui.selectors.tagsOr([]).inputs({});
    expect(emptyOr.matcher({ tags: [] })).toBe(true);
    expect(emptyOr.matcher({})).toBe(true);
  });

  it('scope conditions stack on top of the leaf matcher (ByUid keeps its uid check)', () => {
    const leaf = gui.selectors.tag('billing').selectByUid('probe-uid', {});
    expect(leaf.matcher({ uid: 'probe-uid', tags: ['billing'] })).toBe(true);
    expect(leaf.matcher({ uid: 'probe-uid', tags: [] })).toBe(false);
    expect(leaf.matcher({ uid: 'other-uid', tags: ['billing'] })).toBe(false);
  });

  it('state sets targetState on the emitted leaf', () => {
    const leaf = gui.selectors.state('draft').inputs({});
    expect(leaf.targetState).toBe('draft');
    expect(leaf.matcher({ tags: [] })).toBe(true);
  });

  it('the first state in the chain wins', () => {
    const leaf = gui.selectors.state('draft').tag('billing').state('final').inputs({});
    expect(leaf.targetState).toBe('draft');
    expect(leaf.matcher({ tags: ['billing'] })).toBe(true);
    expect(leaf.matcher({ tags: [] })).toBe(false);
  });

  it('extends the chain immutably', () => {
    const root = gui.selectors;
    const scoped = root.tag('billing');
    expect(scoped).not.toBe(root);

    // The root stays unscoped after deriving a scoped chain from it.
    expect(root.inputs({}).matcher({ tags: [] })).toBe(true);
    expect(scoped.inputs({}).matcher({ tags: [] })).toBe(false);
  });
});
