<script setup lang="ts">
import { RouterLink } from 'vue-router';
</script>

<template>
  <div class="kx-landing">
    <div class="kx-landing__inner">
      <span class="kx-landing__eyebrow">Vue Playground</span>
      <h1 class="kx-landing__title">GolemUI Kitchen Sink</h1>
      <p class="kx-landing__subtitle">
        Two ways to build the same form. Both pipelines render through the unified
        <code>&lt;GuiForm&gt;</code> component and produce identical output — pick the path that
        fits how you author forms.
      </p>

      <div class="kx-landing__grid">
        <RouterLink to="/json/kitchen-sink" class="kx-card kx-card--json">
          <div class="kx-card__head">
            <span class="kx-card__badge">JSON Path</span>
          </div>
          <h2 class="kx-card__title">Declarative form definition</h2>
          <p class="kx-card__desc">
            A plain JSON tree describing layouts, inputs, validators and event handlers. Ideal when
            the form lives in a database, is generated by an external tool, or needs to round-trip
            across services.
          </p>
          <ul class="kx-card__list">
            <li>Schema-driven UIs &amp; backend-defined forms</li>
            <li>Easy to serialize, diff and version</li>
            <li>No build-time dependency on form authors' tooling</li>
          </ul>
          <span class="kx-card__cta">
            Open JSON kitchen sink
            <span class="kx-card__cta__arrow">→</span>
          </span>
        </RouterLink>

        <RouterLink to="/dx/kitchen-sink" class="kx-card kx-card--dx">
          <div class="kx-card__head">
            <span class="kx-card__badge">DX Path</span>
          </div>
          <h2 class="kx-card__title">Type-safe builder API</h2>
          <p class="kx-card__desc">
            Compose forms with the <code>gui.*</code> builders and GSL selectors. The unified
            <code>&lt;GuiForm&gt;</code> runs <code>processDxFacade</code> internally, with
            memoization so the tree only walks once per definition.
          </p>
          <ul class="kx-card__list">
            <li>Autocomplete, refactor safety and inline docs</li>
            <li>Validators &amp; reactive states colocated with widgets</li>
            <li>Selectors apply cross-cutting concerns without prop-drilling</li>
          </ul>
          <span class="kx-card__cta">
            Open DX kitchen sink
            <span class="kx-card__cta__arrow">→</span>
          </span>
        </RouterLink>

        <RouterLink to="/dx/modular" class="kx-card kx-card--modular">
          <div class="kx-card__head">
            <span class="kx-card__badge">DX Modular</span>
          </div>
          <h2 class="kx-card__title">Multi-module tabbed form</h2>
          <p class="kx-card__desc">
            Combine independent <code>DxModule</code> slices into a single tabbed
            <code>&lt;GuiForm&gt;</code> via <code>buildModularDx()</code>. Each module owns its
            layout, data, and reactive states — merged at the boundary.
          </p>
          <ul class="kx-card__list">
            <li>Compose features as self-contained modules</li>
            <li>Tabs auto-generated from module labels</li>
            <li>Data and states merged transparently at runtime</li>
          </ul>
          <span class="kx-card__cta">
            Open modular DX
            <span class="kx-card__cta__arrow">→</span>
          </span>
        </RouterLink>
      </div>
    </div>
  </div>
</template>
