/**
 * Builds the source of the generated validators module with ajv standalone code, so the `json`
 * entry never compiles a schema at runtime. Workers reject the `new Function` call that ajv
 * compiles with. The generator script writes the result. The module is not committed because it
 * is large and ajv renumbers its functions on any schema change. The nx target
 * `generate-validators` builds it before `build` and `vite:test`.
 */
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { ALL_SCHEMAS, FORM_SCHEMA } from '../src/json/schemas/index';
import {
  planStandaloneValidators,
  type StandaloneValidatorPlan,
} from '../src/json/schemas/validator-schemas';

export const GENERATED_HEADER =
  '// GENERATED by libs/gui/mcp/tools/generate-validators.ts - DO NOT EDIT.\n' +
  '// Regenerate with `npm run generate:validators`.\n';

const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Generates the validators module for every schema listed by `planStandaloneValidators`.
 * Its exports are typed by the hand-written `validators.d.ts` next to it.
 * @returns The source of `validators.js`.
 */
export function buildValidatorsModule(): string {
  const plan = planStandaloneValidators(FORM_SCHEMA);
  assertExportNamesAreIdentifiers(plan);
  assertNoFormatKeyword();

  // Same options the runtime Ajv used, plus the options that make ajv return source code.
  // `verbose` stays on because `errors.ts` reads `data` from each error.
  const ajv = new Ajv2020({
    allErrors: true,
    strict: false,
    verbose: true,
    inlineRefs: false,
    code: { source: true, esm: true },
  });
  const registeredSchemaIds = new Set<string>();
  for (const schema of ALL_SCHEMAS) {
    if (typeof schema.$id === 'string' && !registeredSchemaIds.has(schema.$id)) {
      registeredSchemaIds.add(schema.$id);
      ajv.addSchema(schema);
    }
  }
  for (const spec of plan.specs) {
    if (spec.derivedSchema) {
      ajv.addSchema(spec.derivedSchema);
    }
  }

  const schemaIdByExportName: Record<string, string> = {};
  for (const spec of plan.specs) {
    schemaIdByExportName[spec.exportName] = spec.schemaId;
  }
  const standalone = standaloneCode(ajv, schemaIdByExportName);
  assertNoRequireCalls(standalone);

  return `${GENERATED_HEADER}${standalone}\n${buildLookupTables(plan)}`;
}

// An ES module has no `require`. ajv writes `require` for its runtime helpers, so a schema that
// starts to need one must be handled here and not fail later in Node or in a Worker.
function assertNoRequireCalls(code: string): void {
  const requireCalls = new Set(code.match(/\brequire\(\s*["'][^"']*["']\s*\)/g));
  if (requireCalls.size > 0) {
    throw new Error(
      `The generated validators call require, which an ES module does not have: ${[...requireCalls].join(', ')}`,
    );
  }
}

// The generator does not register ajv-formats. A `format` keyword would then be ignored and a
// validator would accept values the runtime Ajv rejected.
function assertNoFormatKeyword(): void {
  const visit = (node: unknown): boolean => {
    if (node === null || typeof node !== 'object') {
      return false;
    }
    if (Array.isArray(node)) {
      return node.some(visit);
    }
    return Object.entries(node).some(
      ([key, value]) => (key === 'format' && typeof value === 'string') || visit(value),
    );
  };
  if (visit(ALL_SCHEMAS)) {
    throw new Error(
      'A schema uses the "format" keyword. Register ajv-formats in the validator generator.',
    );
  }
}

function assertExportNamesAreIdentifiers(plan: StandaloneValidatorPlan): void {
  for (const spec of plan.specs) {
    if (!IDENTIFIER_PATTERN.test(spec.exportName)) {
      throw new Error(`"${spec.exportName}" is not a valid export name`);
    }
  }
}

function buildLookupTables(plan: StandaloneValidatorPlan): string {
  const table = (exportNameByKey: Record<string, string>): string => {
    const lines = Object.entries(exportNameByKey).map(
      ([key, exportName]) => `  ${JSON.stringify(key)}: ${exportName},`,
    );
    return `{\n${lines.join('\n')}\n}`;
  };
  return (
    `export const SHALLOW_WIDGET_VALIDATORS = ${table(plan.shallowExportNameByWidgetType)};\n` +
    `export const VALIDATOR_BRANCH_VALIDATORS = ${table(plan.branchExportNameByValidatorType)};\n` +
    `export const CUSTOM_WIDGET_VALIDATORS = ${table(plan.customExportNameByKind)};\n`
  );
}
