/**
 * Generate the agent-skill reference files from the compile-verified registry in
 * `src/dx/dx-specs.ts`, the same source of truth as `dx_get_spec`, so skill and MCP
 * can never disagree.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  DX_SPECS,
  dxCommonNote,
  dxDocUrl,
  dxFrameworkSetup,
  dxPatterns,
  listDxFactories,
  listDxFrameworks,
} from '../src/dx/dx-specs';

const here = dirname(fileURLToPath(import.meta.url));
const REPO = join(here, '..', '..', '..', '..');

const DOCS_BASE = 'https://golemui.com';

const GENERATED_HEADER =
  '<!-- GENERATED by libs/gui/mcp/tools/generate-skill-refs.ts from the compile-verified\n' +
  '     registry in libs/gui/mcp/src/dx/dx-specs.ts — DO NOT EDIT. Regenerate with\n' +
  '     `npm run generate:skill`. -->';

export function buildDxReference(): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push('');
  lines.push('# GolemUI — TS API (`gui.*`) form-building reference');
  lines.push('');
  lines.push(
    'GolemUI forms are **data, not markup**: a form is an array of field items built with the `gui` ' +
      'builder (imported from `@golemui/gui-shared`). There is NO chained/fluent builder (`gui.form().text()...`) ' +
      'and no `gui.actions.submitButton`. Each item is `gui.<namespace>.<factory>(...)`.',
  );
  lines.push('');
  lines.push(
    'HOW TO USE THIS REFERENCE: read it **once** and write the whole form from it — it is self-sufficient ' +
      'for almost every form, so you should rarely need another fetch. For a widget’s exhaustive options ' +
      'beyond what is here, follow the **Reference:** link printed under that factory below — each is a full ' +
      `absolute URL on ${DOCS_BASE}. The complete page index is at ${DOCS_BASE}/llms.txt. ` +
      'These docs are the authoritative source — do NOT read the `@golemui` TypeScript declarations in ' +
      '`node_modules` or search the filesystem; everything you need is here or one Reference link away. ' +
      'VERIFY when done: write the form to a file and run `npx -y @golemui/gui-mcp check-dx <file.ts>` ' +
      '(exit 0 = compiles against the real `@golemui` types; exit 1 = fix the reported diagnostics and re-run).',
  );
  lines.push('');
  lines.push('General: ' + dxCommonNote());
  lines.push('');
  lines.push('## Host wiring per framework');
  lines.push('');
  lines.push(
    'The `formDef` array is identical everywhere; only the host wrapper changes. ' +
      'Note the submit event name: Vue is the ONLY kebab-case one (`@form-submit`).',
  );
  lines.push('');
  const setup = dxFrameworkSetup();
  for (const fw of listDxFrameworks()) {
    lines.push(`- ${setup[fw]}`);
  }
  lines.push('');
  lines.push('Every example below is compile-checked against the real `@golemui` type declarations.');
  lines.push('');

  // Factory index — the whole surface up front, so the reader knows every real name and
  // signature before scrolling. Never guess a name.
  lines.push('## Factory index');
  lines.push('');
  lines.push(
    'Every `gui.*` factory and its calling convention. Look up the detail below for the ones you use.',
  );
  lines.push('');
  for (const factory of listDxFactories()) {
    lines.push(`- \`${DX_SPECS[factory].call}\``);
  }
  lines.push('');

  for (const factory of listDxFactories()) {
    const s = DX_SPECS[factory];
    lines.push(`## gui.${s.namespace}.${s.factory}`);
    lines.push('');
    lines.push('Call: `' + s.call + '`');
    lines.push('');
    lines.push('```ts');
    lines.push(s.example);
    lines.push('```');
    if (s.notes.length) {
      lines.push('');
      for (const n of s.notes) lines.push(`- ${n}`);
    }
    lines.push('');
    lines.push(`Reference: ${dxDocUrl(s)}`);
    lines.push('');
  }

  lines.push('# Patterns');
  lines.push('');
  lines.push('Cross-cutting patterns that apply to every factory (not a factory themselves).');
  lines.push('');
  for (const p of dxPatterns()) {
    lines.push(`## ${p.title}`);
    lines.push('');
    lines.push('```ts');
    lines.push(p.example);
    lines.push('```');
    lines.push('');
    for (const n of p.notes) lines.push(`- ${n}`);
    lines.push('');
  }
  return lines.join('\n');
}

export function buildWidgetsIndex(): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push('');
  lines.push('# GolemUI widgets — documentation index');
  lines.push('');
  lines.push(
    'Every widget’s exhaustive reference page (props, per-prop examples, CSS variables), as ' +
      'plain-markdown URLs. Fetch the `dx` URL when writing `gui.*` TypeScript, the `json` URL ' +
      'when writing JSON form definitions — never mix syntaxes from the two. ' +
      `The full docs index (all topics, not just widgets) is ${DOCS_BASE}/llms.txt.`,
  );
  lines.push('');

  // Group factories by their target page (some deliberately share one: flex/grid variants).
  const groups: Record<string, { title: string; rows: Map<string, string[]> }> = {
    inputs: { title: 'Input widgets', rows: new Map() },
    actions: { title: 'Action widgets', rows: new Map() },
    displays: { title: 'Display widgets', rows: new Map() },
    layouts: { title: 'Layout widgets', rows: new Map() },
  };
  for (const factory of listDxFactories()) {
    const s = DX_SPECS[factory];
    const rows = groups[s.namespace].rows;
    rows.set(s.docSlug, [...(rows.get(s.docSlug) ?? []), `gui.${s.namespace}.${s.factory}`]);
  }

  for (const ns of ['inputs', 'actions', 'displays', 'layouts'] as const) {
    const { title, rows } = groups[ns];
    lines.push(`## ${title}`);
    lines.push('');
    for (const [, factories] of [...rows.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      const s = DX_SPECS[factories[0].split('.')[2]];
      lines.push(`- ${factories.map((f) => `\`${f}\``).join(', ')} — ${dxDocUrl(s)} (json: ${dxDocUrl(s, 'json')})`);
    }
    const overview = `${DOCS_BASE}/dx/widgets-reference/${
      { inputs: 'input-fields', actions: 'interactive-fields', displays: 'display-fields', layouts: 'layout-fields' }[ns]
    }/overview.md`;
    lines.push(`- Category overview — ${overview}`);
    lines.push('');
  }
  return lines.join('\n');
}

const REFS = join(REPO, 'skills', 'golemui', 'references');
const DIST = join(REPO, 'dist', 'libs', 'gui', 'mcp');

const dxReference = buildDxReference();
const widgetsIndex = buildWidgetsIndex();

mkdirSync(REFS, { recursive: true });
mkdirSync(DIST, { recursive: true });
writeFileSync(join(REFS, 'forms-dx.md'), dxReference + '\n', 'utf-8');
writeFileSync(join(REFS, 'widgets-index.md'), widgetsIndex + '\n', 'utf-8');
writeFileSync(join(DIST, 'llms-gui-dx.txt'), dxReference + '\n', 'utf-8');

console.log(
  `Wrote forms-dx.md (${dxReference.length} bytes), widgets-index.md (${widgetsIndex.length} bytes), ` +
    `llms-gui-dx.txt — ${listDxFactories().length} factories.`,
);
