name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - uses: nrwl/nx-set-shas@v4

      - name: Install dependencies
        run: npm ci

      - run: npm run lint:affected

      - name: Cypress component testing
        run: npx nx affected --target=component-test --parallel=1 --browser chrome --headless
        env:
          # Nx Daemon can sometimes hold onto memory. Forcing it off ensures that every time a task runs, it starts with a clean slate.
          NX_DAEMON: false
          # Tell Node to cap its heap at 4GB, leaving ~3GB for the OS, the Browser (Chrome), and the Dev Server.
          # Prevents Node and the Browser from fighting over the last bit of RAM
          NODE_OPTIONS: '--max-old-space-size=4096'
