name: release

on:
  push:
    branches:
      - main

concurrency:
  group: release-main
  cancel-in-progress: true

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'golemui/formforge'
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          cache: "npm"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build affected / all packages
        run: npx nx run-many --target=build --all --parallel

      - name: Release a new package
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
