name: Release

# TODO: Re-enable automatic triggers when ready to go public with provenance
# on:
#   push:
#     branches:
#       - main
#   workflow_run:
#     workflows: ['CI']
#     types:
#       - completed
on:
  workflow_dispatch:

jobs:
  release:
    # if: >
    #   github.event.workflow_run.conclusion == 'success' &&
    #   github.event.workflow_run.head_branch == 'main'
    name: Nx Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Configure git remote with PAT
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.RELEASE_PAT }}@github.com/${{ github.repository }}.git

      - name: config git user
        run: |
          git config --global user.name "Raúl Jiménez"
          git config --global user.email "elecash@gmail.com"

      - name: Release to Github and NPM
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096 --trace-warnings"
          # We need more listeners here
          node -e "require('events').EventEmitter.defaultMaxListeners = 20" && npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
