// GENERATED by libs/gui/schemas/tools/generate-schemas.ts from src/lib/widget-manifest.ts. DO NOT EDIT.
// Regenerate with `npm run generate:schemas`.
import calendarSchema from './lib/components/calendar.schema.json';
import datetimecalendarSchema from './lib/components/datetimecalendar.schema.json';
import checkboxSchema from './lib/components/checkbox.schema.json';
import currencySchema from './lib/components/currency.schema.json';
import dateinputSchema from './lib/components/dateinput.schema.json';
import datepickerSchema from './lib/components/datepicker.schema.json';
import datetimeinputSchema from './lib/components/datetimeinput.schema.json';
import datetimepickerSchema from './lib/components/datetimepicker.schema.json';
import dropdownSchema from './lib/components/dropdown.schema.json';
import listSchema from './lib/components/list.schema.json';
import markdownSchema from './lib/components/markdown.schema.json';
import numberSchema from './lib/components/number.schema.json';
import passwordSchema from './lib/components/password.schema.json';
import radiogroupSchema from './lib/components/radiogroup.schema.json';
import rangecalendarSchema from './lib/components/rangecalendar.schema.json';
import rangedateinputSchema from './lib/components/rangedateinput.schema.json';
import rangedatepickerSchema from './lib/components/rangedatepicker.schema.json';
import rangedatetimeinputSchema from './lib/components/rangedatetimeinput.schema.json';
import rangedatetimecalendarSchema from './lib/components/rangedatetimecalendar.schema.json';
import rangedatetimepickerSchema from './lib/components/rangedatetimepicker.schema.json';
import rangetimeinputSchema from './lib/components/rangetimeinput.schema.json';
import rangetimepickerSchema from './lib/components/rangetimepicker.schema.json';
import repeaterSchema from './lib/components/repeater.schema.json';
import selectSchema from './lib/components/select.schema.json';
import tagsSchema from './lib/components/tags.schema.json';
import textareaSchema from './lib/components/textarea.schema.json';
import textinputSchema from './lib/components/textinput.schema.json';
import timeinputSchema from './lib/components/timeinput.schema.json';
import timepickerSchema from './lib/components/timepicker.schema.json';
import toggleSchema from './lib/components/toggle.schema.json';
import accordionSchema from './lib/components/accordion.schema.json';
import flexSchema from './lib/components/flex.schema.json';
import gridSchema from './lib/components/grid.schema.json';
import tabsSchema from './lib/components/tabs.schema.json';
import alertSchema from './lib/components/alert.schema.json';
import markdowntextSchema from './lib/components/markdowntext.schema.json';
import buttonSchema from './lib/components/button.schema.json';
import customSchema from './lib/components/custom.schema.json';
export { default as commonSchema } from './lib/core/common.schema.json';
export { default as validatorsSchema } from './lib/core/validators.schema.json';
export { default as formSchema } from './lib/form.schema.json';
export { default as layoutWidgetSchema } from './lib/layout-widget.schema.json';
export { default as widgetsSchema } from './lib/widgets.schema.json';
export { guiCoreRegistrations } from './lib/core-registrations';
export {
  calendarSchema,
  datetimecalendarSchema,
  checkboxSchema,
  currencySchema,
  dateinputSchema,
  datepickerSchema,
  datetimeinputSchema,
  datetimepickerSchema,
  dropdownSchema,
  listSchema,
  markdownSchema,
  numberSchema,
  passwordSchema,
  radiogroupSchema,
  rangecalendarSchema,
  rangedateinputSchema,
  rangedatepickerSchema,
  rangedatetimeinputSchema,
  rangedatetimecalendarSchema,
  rangedatetimepickerSchema,
  rangetimeinputSchema,
  rangetimepickerSchema,
  repeaterSchema,
  selectSchema,
  tagsSchema,
  textareaSchema,
  textinputSchema,
  timeinputSchema,
  timepickerSchema,
  toggleSchema,
  accordionSchema,
  flexSchema,
  gridSchema,
  tabsSchema,
  alertSchema,
  markdowntextSchema,
  buttonSchema,
  customSchema,
};

/**
 * Component schemas keyed by widget `type`. Excludes the custom-widget
 * fallback schema (it has no single `type` const) and widget types that
 * have no JSON schema.
 */
export const COMPONENT_SCHEMAS_BY_TYPE = {
  calendar: calendarSchema,
  dateTimeCalendar: datetimecalendarSchema,
  checkbox: checkboxSchema,
  currency: currencySchema,
  dateInput: dateinputSchema,
  datePicker: datepickerSchema,
  dateTimeInput: datetimeinputSchema,
  dateTimePicker: datetimepickerSchema,
  dropdown: dropdownSchema,
  list: listSchema,
  markdown: markdownSchema,
  number: numberSchema,
  password: passwordSchema,
  radiogroup: radiogroupSchema,
  rangeCalendar: rangecalendarSchema,
  rangeDateInput: rangedateinputSchema,
  rangeDatePicker: rangedatepickerSchema,
  rangeDateTimeInput: rangedatetimeinputSchema,
  rangeDateTimeCalendar: rangedatetimecalendarSchema,
  rangeDateTimePicker: rangedatetimepickerSchema,
  rangeTimeInput: rangetimeinputSchema,
  rangeTimePicker: rangetimepickerSchema,
  repeater: repeaterSchema,
  select: selectSchema,
  tags: tagsSchema,
  textarea: textareaSchema,
  textinput: textinputSchema,
  timeInput: timeinputSchema,
  timePicker: timepickerSchema,
  toggle: toggleSchema,
  accordion: accordionSchema,
  flex: flexSchema,
  grid: gridSchema,
  tabs: tabsSchema,
  alert: alertSchema,
  markdownText: markdowntextSchema,
  button: buttonSchema,
} as const;
