// GENERATED by libs/gui/schemas/tools/generate-schemas.ts from src/lib/widget-manifest.ts. DO NOT EDIT.
// Regenerate with `npm run generate:schemas`.
import commonSchemaJson from './lib/core/common.schema.json';
import rangesSchemaJson from './lib/ranges.schema.json';
import validatorsSchemaJson from './lib/validators.schema.json';
import formSchemaJson from './lib/form.schema.json';
import layoutWidgetSchemaJson from './lib/layout-widget.schema.json';
import widgetsSchemaJson from './lib/widgets.schema.json';
import calendarSchemaJson from './lib/components/calendar.schema.json';
import datetimecalendarSchemaJson from './lib/components/datetimecalendar.schema.json';
import checkboxSchemaJson from './lib/components/checkbox.schema.json';
import currencySchemaJson from './lib/components/currency.schema.json';
import dateinputSchemaJson from './lib/components/dateinput.schema.json';
import datepickerSchemaJson from './lib/components/datepicker.schema.json';
import datetimeinputSchemaJson from './lib/components/datetimeinput.schema.json';
import datetimepickerSchemaJson from './lib/components/datetimepicker.schema.json';
import dropdownSchemaJson from './lib/components/dropdown.schema.json';
import listSchemaJson from './lib/components/list.schema.json';
import markdownSchemaJson from './lib/components/markdown.schema.json';
import multidropdownSchemaJson from './lib/components/multidropdown.schema.json';
import multilistSchemaJson from './lib/components/multilist.schema.json';
import numberSchemaJson from './lib/components/number.schema.json';
import passwordSchemaJson from './lib/components/password.schema.json';
import radiogroupSchemaJson from './lib/components/radiogroup.schema.json';
import rangecalendarSchemaJson from './lib/components/rangecalendar.schema.json';
import rangedateinputSchemaJson from './lib/components/rangedateinput.schema.json';
import rangedatepickerSchemaJson from './lib/components/rangedatepicker.schema.json';
import rangedatetimeinputSchemaJson from './lib/components/rangedatetimeinput.schema.json';
import rangedatetimecalendarSchemaJson from './lib/components/rangedatetimecalendar.schema.json';
import rangedatetimepickerSchemaJson from './lib/components/rangedatetimepicker.schema.json';
import rangetimeinputSchemaJson from './lib/components/rangetimeinput.schema.json';
import rangetimepickerSchemaJson from './lib/components/rangetimepicker.schema.json';
import repeaterSchemaJson from './lib/components/repeater.schema.json';
import selectSchemaJson from './lib/components/select.schema.json';
import tagsSchemaJson from './lib/components/tags.schema.json';
import textareaSchemaJson from './lib/components/textarea.schema.json';
import textinputSchemaJson from './lib/components/textinput.schema.json';
import timeinputSchemaJson from './lib/components/timeinput.schema.json';
import timepickerSchemaJson from './lib/components/timepicker.schema.json';
import toggleSchemaJson from './lib/components/toggle.schema.json';
import accordionSchemaJson from './lib/components/accordion.schema.json';
import flexSchemaJson from './lib/components/flex.schema.json';
import gridSchemaJson from './lib/components/grid.schema.json';
import tabsSchemaJson from './lib/components/tabs.schema.json';
import alertSchemaJson from './lib/components/alert.schema.json';
import markdowntextSchemaJson from './lib/components/markdowntext.schema.json';
import buttonSchemaJson from './lib/components/button.schema.json';
import customSchemaJson from './lib/components/custom.schema.json';

export const commonSchema: Record<string, unknown> = commonSchemaJson;
export const rangesSchema: Record<string, unknown> = rangesSchemaJson;
export const validatorsSchema: Record<string, unknown> = validatorsSchemaJson;
export const formSchema: Record<string, unknown> = formSchemaJson;
export const layoutWidgetSchema: Record<string, unknown> = layoutWidgetSchemaJson;
export const widgetsSchema: Record<string, unknown> = widgetsSchemaJson;
export const calendarSchema: Record<string, unknown> = calendarSchemaJson;
export const datetimecalendarSchema: Record<string, unknown> = datetimecalendarSchemaJson;
export const checkboxSchema: Record<string, unknown> = checkboxSchemaJson;
export const currencySchema: Record<string, unknown> = currencySchemaJson;
export const dateinputSchema: Record<string, unknown> = dateinputSchemaJson;
export const datepickerSchema: Record<string, unknown> = datepickerSchemaJson;
export const datetimeinputSchema: Record<string, unknown> = datetimeinputSchemaJson;
export const datetimepickerSchema: Record<string, unknown> = datetimepickerSchemaJson;
export const dropdownSchema: Record<string, unknown> = dropdownSchemaJson;
export const listSchema: Record<string, unknown> = listSchemaJson;
export const markdownSchema: Record<string, unknown> = markdownSchemaJson;
export const multidropdownSchema: Record<string, unknown> = multidropdownSchemaJson;
export const multilistSchema: Record<string, unknown> = multilistSchemaJson;
export const numberSchema: Record<string, unknown> = numberSchemaJson;
export const passwordSchema: Record<string, unknown> = passwordSchemaJson;
export const radiogroupSchema: Record<string, unknown> = radiogroupSchemaJson;
export const rangecalendarSchema: Record<string, unknown> = rangecalendarSchemaJson;
export const rangedateinputSchema: Record<string, unknown> = rangedateinputSchemaJson;
export const rangedatepickerSchema: Record<string, unknown> = rangedatepickerSchemaJson;
export const rangedatetimeinputSchema: Record<string, unknown> = rangedatetimeinputSchemaJson;
export const rangedatetimecalendarSchema: Record<string, unknown> = rangedatetimecalendarSchemaJson;
export const rangedatetimepickerSchema: Record<string, unknown> = rangedatetimepickerSchemaJson;
export const rangetimeinputSchema: Record<string, unknown> = rangetimeinputSchemaJson;
export const rangetimepickerSchema: Record<string, unknown> = rangetimepickerSchemaJson;
export const repeaterSchema: Record<string, unknown> = repeaterSchemaJson;
export const selectSchema: Record<string, unknown> = selectSchemaJson;
export const tagsSchema: Record<string, unknown> = tagsSchemaJson;
export const textareaSchema: Record<string, unknown> = textareaSchemaJson;
export const textinputSchema: Record<string, unknown> = textinputSchemaJson;
export const timeinputSchema: Record<string, unknown> = timeinputSchemaJson;
export const timepickerSchema: Record<string, unknown> = timepickerSchemaJson;
export const toggleSchema: Record<string, unknown> = toggleSchemaJson;
export const accordionSchema: Record<string, unknown> = accordionSchemaJson;
export const flexSchema: Record<string, unknown> = flexSchemaJson;
export const gridSchema: Record<string, unknown> = gridSchemaJson;
export const tabsSchema: Record<string, unknown> = tabsSchemaJson;
export const alertSchema: Record<string, unknown> = alertSchemaJson;
export const markdowntextSchema: Record<string, unknown> = markdowntextSchemaJson;
export const buttonSchema: Record<string, unknown> = buttonSchemaJson;
export const customSchema: Record<string, unknown> = customSchemaJson;

/** Component schemas keyed by widget `type`. Excludes the custom fallback and schema-less types. */
export const COMPONENT_SCHEMAS_BY_TYPE = {
  calendar: calendarSchema,
  dateTimeCalendar: datetimecalendarSchema,
  checkbox: checkboxSchema,
  currency: currencySchema,
  dateInput: dateinputSchema,
  datePicker: datepickerSchema,
  dateTimeInput: datetimeinputSchema,
  dateTimePicker: datetimepickerSchema,
  dropdown: dropdownSchema,
  list: listSchema,
  markdown: markdownSchema,
  multiDropdown: multidropdownSchema,
  multiList: multilistSchema,
  number: numberSchema,
  password: passwordSchema,
  radiogroup: radiogroupSchema,
  rangeCalendar: rangecalendarSchema,
  rangeDateInput: rangedateinputSchema,
  rangeDatePicker: rangedatepickerSchema,
  rangeDateTimeInput: rangedatetimeinputSchema,
  rangeDateTimeCalendar: rangedatetimecalendarSchema,
  rangeDateTimePicker: rangedatetimepickerSchema,
  rangeTimeInput: rangetimeinputSchema,
  rangeTimePicker: rangetimepickerSchema,
  repeater: repeaterSchema,
  select: selectSchema,
  tags: tagsSchema,
  textarea: textareaSchema,
  textinput: textinputSchema,
  timeInput: timeinputSchema,
  timePicker: timepickerSchema,
  toggle: toggleSchema,
  accordion: accordionSchema,
  flex: flexSchema,
  grid: gridSchema,
  tabs: tabsSchema,
  alert: alertSchema,
  markdownText: markdowntextSchema,
  button: buttonSchema,
} as const;
